Repository godot-rust/gdext, pull requests merged in 2022-11, with the labels that each got.

#13 fixed regex parsing for godot4 beta4
  godot-codegen/src/godot_version.rs
Labels: bug, c: ffi

#15 fix(build): Builds on Mac would fail because the env variable `LLVM_PATH` wasn't hardcoded properly
  godot-ffi/build.rs
Labels: bug, c: tooling

#20 Fix null-check against uninitialized pointer in `Gd::from_sys_init_opt()`
  godot-core/src/obj/gd.rs
Labels: bug, c: ffi

#21 Add link to library for macos in README
  ReadMe.md
Labels: documentation
