Repository godot-rust/gdext, pull requests merged in 2023-09, with the labels that each got.

#398 Benchmark infrastructure
  godot-macros/src/bench.rs
  godot-macros/src/lib.rs
  godot-macros/src/util/kv_parser.rs
  godot-macros/src/util/mod.rs
  godot/src/lib.rs
  itest/godot/TestRunner.gd
  itest/rust/src/benchmarks/mod.rs
  itest/rust/src/common.rs
  itest/rust/src/framework/bencher.rs
  itest/rust/src/framework/mod.rs
  itest/rust/src/framework/runner.rs
  itest/rust/src/lib.rs
  itest/rust/src/register_tests/derive_variant/enums_skip.rs
  itest/rust/src/register_tests/derive_variant/mod.rs
  itest/rust/src/register_tests/derive_variant/structs_skip.rs
  itest/rust/src/register_tests/derive_variant_test.rs
  itest/rust/src/register_tests/mod.rs
Labels: feature, c: tooling

#387 Cache function pointers in global tables
  godot-bindings/src/watch.rs
  godot-codegen/src/api_parser.rs
  godot-codegen/src/central_generator.rs
  godot-codegen/src/class_generator.rs
  godot-codegen/src/codegen_special_cases.rs
  godot-codegen/src/context.rs
  godot-codegen/src/lib.rs
  godot-codegen/src/special_cases.rs
  godot-codegen/src/util.rs
  godot-core/src/init/mod.rs
  godot-core/src/lib.rs
  godot-ffi/src/godot_ffi.rs
  godot-ffi/src/lib.rs
  godot-ffi/src/string_cache.rs
  godot-ffi/src/toolbox.rs
  godot-macros/src/class/data_models/func.rs
  godot/src/lib.rs
Labels: feature, c: engine

#405 Exclude OpenXR from macOS in Godot < 4.2; run `codegen-full` in full-ci
  .github/workflows/full-ci.yml
  Cargo.toml
  godot-codegen/src/special_cases.rs
  godot-codegen/src/util.rs
Labels: bug, c: engine

#408 Array-based function pointer tables
  godot-codegen/src/central_generator.rs
  godot-codegen/src/class_generator.rs
  godot-codegen/src/context.rs
  godot-codegen/src/lib.rs
  godot-codegen/src/special_cases.rs
  godot-codegen/src/util.rs
  godot-core/src/lib.rs
  godot-ffi/src/toolbox.rs
Labels: quality-of-life, c: engine

#409 `Share` trait: deprecate + replace with `Clone`
  examples/dodge-the-creeps/rust/src/main_scene.rs
  godot-core/src/builtin/array.rs
  godot-core/src/builtin/dictionary.rs
  godot-core/src/builtin/string/godot_string.rs
  godot-core/src/builtin/string/node_path.rs
  godot-core/src/builtin/string/string_name.rs
  godot-core/src/engine.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/traits.rs
  godot/src/lib.rs
  itest/rust/src/builtin_tests/containers/array_test.rs
  itest/rust/src/builtin_tests/containers/callable_test.rs
  itest/rust/src/builtin_tests/containers/dictionary_test.rs
  itest/rust/src/builtin_tests/containers/signal_test.rs
  itest/rust/src/builtin_tests/containers/variant_test.rs
  itest/rust/src/engine_tests/native_structures_test.rs
  itest/rust/src/engine_tests/node_test.rs
  itest/rust/src/object_tests/object_test.rs
  itest/rust/src/object_tests/virtual_methods_test.rs
Labels: quality-of-life, c: core

#415 Delegate majority of engine codegen to type system
  ReadMe.md
  godot-codegen/src/central_generator.rs
  godot-codegen/src/class_generator.rs
  godot-codegen/src/codegen_special_cases.rs
  godot-codegen/src/lib.rs
  godot-codegen/src/util.rs
  godot-codegen/src/utilities_generator.rs
  godot-core/src/builtin/meta/mod.rs
  godot-core/src/builtin/meta/return_marshal.rs
  godot-core/src/builtin/meta/signature.rs
  godot-core/src/lib.rs
  godot-ffi/src/gdextension_plus.rs
  godot-ffi/src/godot_ffi.rs
  godot-ffi/src/toolbox.rs
  godot-macros/src/class/data_models/func.rs
Labels: quality-of-life, c: engine

#417 Ensure object validity in class method calls
  .github/composite/godot-itest/action.yml
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  godot-codegen/src/class_generator.rs
  godot-core/src/builtin/meta/signature.rs
  godot-core/src/engine.rs
  godot-core/src/obj/gd.rs
  itest/rust/src/object_tests/object_test.rs
Labels: feature, c: core, c: engine

#393 Add editor plugins, and registration of classes at the proper initialization level
  godot-codegen/src/class_generator.rs
  godot-codegen/src/codegen_special_cases.rs
  godot-codegen/src/special_cases.rs
  godot-codegen/src/util.rs
  godot-core/src/init/mod.rs
  godot-core/src/lib.rs
  godot-core/src/obj/traits.rs
  godot-core/src/registry.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/class/godot_api.rs
  godot-macros/src/lib.rs
  godot-macros/src/util/kv_parser.rs
  itest/rust/src/object_tests/object_test.rs
  itest/rust/src/register_tests/constant_test.rs
Labels: feature, c: bind

#418 Callables for custom Rust functions
  godot-core/src/builtin/array.rs
  godot-core/src/builtin/callable.rs
  godot-core/src/builtin/meta/signature.rs
  godot-core/src/builtin/variant/mod.rs
  godot-core/src/registry.rs
  itest/rust/src/builtin_tests/containers/callable_test.rs
  itest/rust/src/framework/runner.rs
Labels: feature, c: core

#424 Feature-gate Godot experimental APIs
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  godot-codegen/Cargo.toml
  godot-codegen/src/special_cases.rs
  godot-core/Cargo.toml
  godot-core/src/obj/guards.rs
  godot-core/src/storage.rs
  godot-ffi/Cargo.toml
  godot/Cargo.toml
  godot/src/lib.rs
Labels: quality-of-life, c: engine

#436 Smaller integration and unit-test updates (NaN eq, list failed, ...)
  .github/workflows/full-ci.yml
  godot-bindings/Cargo.toml
  godot-bindings/src/godot_version.rs
  godot-bindings/src/lib.rs
  godot-core/src/builtin/callable.rs
  godot-core/src/builtin/dictionary.rs
  godot-ffi/src/toolbox.rs
  itest/godot/ManualFfiTests.gd
  itest/godot/TestRunner.gd
  itest/rust/src/builtin_tests/containers/dictionary_test.rs
  itest/rust/src/framework/runner.rs
Labels: quality-of-life, c: core, c: tooling

#433 doc: use actual type names in `Packed*Array` documentation
  godot-core/src/builtin/packed_array.rs
Labels: quality-of-life, c: core

#427 Add `StringName::from_latin1_with_nul()`, direct construction in `String::from(&str)`
  godot-codegen/src/util.rs
  godot-core/src/builtin/string/macros.rs
  godot-core/src/builtin/string/node_path.rs
  godot-core/src/builtin/string/string_name.rs
  godot-core/src/log.rs
  godot-ffi/src/toolbox.rs
  itest/rust/src/builtin_tests/string/string_name_test.rs
Labels: feature, c: core
