Repository godot-rust/gdext, pull requests merged in 2023-08, with the labels that each got.

#361 Added 32-bit support.
  godot-codegen/src/api_parser.rs
  godot-codegen/src/central_generator.rs
  godot-codegen/src/class_generator.rs
  godot-ffi/src/opaque.rs
Labels: feature, c: tooling, c: engine

#369 `IndexEnum` trait, doc cleanups w.r.t visibility + notifications
  godot-codegen/src/class_generator.rs
  godot-codegen/src/context.rs
  godot-codegen/src/lib.rs
  godot-codegen/src/util.rs
  godot-core/src/obj/traits.rs
  godot-ffi/src/godot_ffi.rs
  itest/rust/src/codegen_test.rs
Labels: documentation, quality-of-life

#370 Move `Deref/DerefMut` out of `T` to `Gd<T>`; `InstanceStorage` safety
  .github/workflows/minimal-ci.yml
  examples/dodge-the-creeps/rust/src/main_scene.rs
  examples/dodge-the-creeps/rust/src/player.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/traits.rs
  godot-core/src/registry.rs
  godot-core/src/storage.rs
  godot-macros/src/derive_godot_class/mod.rs
  itest/rust/src/base_test.rs
  itest/rust/src/callable_test.rs
  itest/rust/src/codegen_test.rs
  itest/rust/src/native_structures_test.rs
  itest/rust/src/object_test.rs
  itest/rust/src/property_test.rs
  itest/rust/src/signal_test.rs
Labels: quality-of-life, ub

#371 #[derive(Property, Export)] for enums
  godot-macros/src/derive_export.rs
  godot-macros/src/derive_property.rs
  godot-macros/src/lib.rs
  godot/src/lib.rs
  itest/rust/src/property_test.rs
Labels: feature, c: bind

#374 `#[class(tool)]` for per-class editor run behavior
  godot-core/src/builtin/real.rs
  godot-core/src/engine.rs
  godot-core/src/init/mod.rs
  godot-core/src/lib.rs
  godot-core/src/registry.rs
  godot-ffi/src/lib.rs
  godot-macros/src/derive_from_variant.rs
  godot-macros/src/derive_godot_class/mod.rs
  godot-macros/src/derive_to_variant.rs
  godot-macros/src/godot_api.rs
  godot-macros/src/lib.rs
  godot-macros/src/method_registration/mod.rs
  godot-macros/src/method_registration/register_method.rs
  godot-macros/src/method_registration/virtual_method_callback.rs
  godot-macros/src/util/mod.rs
Labels: feature, c: bind

#375 Enforce rustdoc checks in CI
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  godot-core/src/builtin/array.rs
  godot-core/src/builtin/callable.rs
  godot-core/src/builtin/color.rs
  godot-core/src/builtin/math/float.rs
  godot-core/src/builtin/plane.rs
  godot-core/src/builtin/real.rs
  godot-core/src/builtin/string/godot_string.rs
  godot-core/src/builtin/transform2d.rs
  godot-core/src/builtin/transform3d.rs
  godot-core/src/builtin/vectors/vector2i.rs
  godot-core/src/builtin/vectors/vector3i.rs
  godot-core/src/builtin/vectors/vector4.rs
  godot-core/src/builtin/vectors/vector4i.rs
  godot-core/src/engine.rs
  godot-core/src/obj/gd.rs
  godot-ffi/src/compat/compat_4_1.rs
  godot-ffi/src/godot_ffi.rs
  godot-macros/src/lib.rs
Labels: feature, c: tooling

#378 Feature/func renaming
  godot-macros/src/derive_godot_class/property/field_var.rs
  godot-macros/src/godot_api.rs
  godot-macros/src/method_registration/mod.rs
  godot-macros/src/method_registration/register_method.rs
  itest/godot/ManualFfiTests.gd
  itest/rust/src/func_test.rs
  itest/rust/src/lib.rs
Labels: feature, c: bind

#386 Update Godot version to 4.1.1, compat to 4.0.4
  .github/composite/godot-install/action.yml
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  godot-bindings/Cargo.toml
  godot-core/src/lib.rs
Labels: feature, c: tooling

#389 Cleanup some minor things
  godot-codegen/src/class_generator.rs
  godot-core/src/builtin/variant/variant_traits.rs
  godot-core/src/obj/gd.rs
  godot-ffi/src/plugins.rs
  itest/rust/src/object_test.rs
  itest/rust/src/option_ffi_test.rs
Labels: quality-of-life, c: core

#377 Improve API soundness wrt reference counted `Gd`
  godot-core/src/obj/gd.rs
  godot-core/src/obj/traits.rs
Labels: bug, c: core, ub
