Repository godot-rust/gdext, pull requests merged in 2023-07, with the labels that each got.

#322 Default parameters in Engine API + meta param/return types
  examples/dodge-the-creeps/rust/src/hud.rs
  examples/dodge-the-creeps/rust/src/main_scene.rs
  examples/dodge-the-creeps/rust/src/mob.rs
  examples/dodge-the-creeps/rust/src/player.rs
  godot-codegen/Cargo.toml
  godot-codegen/src/api_parser.rs
  godot-codegen/src/central_generator.rs
  godot-codegen/src/class_generator.rs
  godot-codegen/src/context.rs
  godot-codegen/src/lib.rs
  godot-codegen/src/special_cases.rs
  godot-codegen/src/util.rs
  godot-codegen/src/utilities_generator.rs
  godot-core/src/builtin/callable.rs
  godot-core/src/builtin/transform2d.rs
  godot-core/src/builtin/transform3d.rs
  godot-core/src/builtin/vectors/vector_axis.rs
  godot-core/src/engine.rs
  godot-core/src/lib.rs
  itest/rust/build.rs
  itest/rust/src/array_test.rs
  itest/rust/src/callable_test.rs
  itest/rust/src/node_test.rs
  itest/rust/src/object_test.rs
  itest/rust/src/signal_test.rs
  itest/rust/src/virtual_methods_test.rs
Labels: feature, c: engine

#323 add some static asserts for `Rid`'s layout
  godot-core/src/builtin/rid.rs
Labels: quality-of-life, c: ffi

#325 Address sanitizers for Rust
  .github/composite/godot-itest/action.yml
  .github/composite/rust/action.yml
  .github/workflows/full-ci.yml
  godot-codegen/src/central_generator.rs
  godot-codegen/src/class_generator.rs
  godot-codegen/src/util.rs
  godot-core/src/builtin/meta/signature.rs
  godot-core/src/macros.rs
  godot-macros/src/method_registration/register_method.rs
  godot-macros/src/method_registration/virtual_method_callback.rs
Labels: feature, c: tooling

#331 Update to Godot 4.1
  .github/composite/godot-install/action.yml
  .github/composite/godot-itest/action.yml
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  examples/dodge-the-creeps/godot/DodgeTheCreeps.gdextension
  godot-bindings/Cargo.toml
  itest/godot/itest.gdextension
Labels: feature, c: tooling, c: engine

#251 Derive skip
  godot-macros/src/derive_from_variant.rs
  godot-macros/src/derive_to_variant.rs
  godot-macros/src/lib.rs
  godot-macros/src/util/kv_parser.rs
  godot-macros/src/util/mod.rs
  itest/rust/src/derive_variant.rs
  itest/rust/src/derive_variant/enums_skip.rs
  itest/rust/src/derive_variant/mod.rs
  itest/rust/src/derive_variant/structs_skip.rs
  itest/rust/src/variant_test.rs
Labels: feature, c: core

#308 adds --filtering option to check.sh
  check.sh
  itest/godot/TestRunner.gd
  itest/godot/project.godot
  itest/rust/src/lib.rs
  itest/rust/src/runner.rs
Labels: feature, c: tooling

#336 Add `instance_id_or_none_unchecked` to `Gd`
  godot-core/src/obj/gd.rs
Labels: feature, c: core

#337 Migrate from bors to GitHub merge queues
  .github/bors.toml
  .github/composite/rust/action.yml
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  .github/workflows/update-docs.yml
Labels: feature, c: tooling

#330 Add extension trait for floats
  godot-core/src/builtin/basis.rs
  godot-core/src/builtin/math/approx_eq.rs
  godot-core/src/builtin/math/float.rs
  godot-core/src/builtin/math/mod.rs
  godot-core/src/builtin/plane.rs
  godot-core/src/builtin/projection.rs
  godot-core/src/builtin/quaternion.rs
  godot-core/src/builtin/transform2d.rs
  godot-core/src/builtin/vectors/vector2.rs
  godot-core/src/builtin/vectors/vector3.rs
  godot-core/src/builtin/vectors/vector4.rs
  godot-core/src/builtin/vectors/vector_macros.rs
  godot/src/lib.rs
Labels: quality-of-life, c: core

#321 Add support for exporting constants
  godot-codegen/src/class_generator.rs
  godot-codegen/src/interface_generator.rs
  godot-codegen/src/lib.rs
  godot-core/src/builtin/meta/mod.rs
  godot-core/src/builtin/meta/registration/constant.rs
  godot-core/src/builtin/meta/registration/method.rs
  godot-core/src/builtin/meta/registration/mod.rs
  godot-core/src/builtin/meta/signature.rs
  godot-core/src/builtin/variant/impls.rs
  godot-core/src/obj/traits.rs
  godot-core/src/registry.rs
  godot-macros/src/godot_api.rs
  godot-macros/src/method_registration/register_method.rs
  godot-macros/src/util/list_parser.rs
  itest/rust/src/lib.rs
  itest/rust/src/object_test.rs
  itest/rust/src/registration/constant_test.rs
  itest/rust/src/registration/mod.rs
  itest/rust/src/virtual_methods_test.rs
Labels: feature, c: bind

#340 Make `with_checked_type` return `Result<Self, VariantConversionError>`
  godot-core/src/builtin/array.rs
  itest/rust/src/array_test.rs
Labels: bug, c: core

#342 Let bitfields accept any ordinal, not just its individual flags.
  godot-codegen/src/lib.rs
  godot-codegen/src/util.rs
  itest/rust/src/enum_test.rs
Labels: bug, c: engine

#341 Refactor method registration; allow `_` as parameter name in `#[func]`
  godot-core/src/builtin/variant/mod.rs
  godot-core/src/lib.rs
  godot-core/src/macros.rs
  godot-core/src/obj/gd.rs
  godot-macros/src/derive_godot_class/mod.rs
  godot-macros/src/derive_godot_class/property/field_var.rs
  godot-macros/src/godot_api.rs
  godot-macros/src/method_registration/mod.rs
  godot-macros/src/method_registration/register_method.rs
  godot-macros/src/method_registration/virtual_method_callback.rs
  godot-macros/src/util/mod.rs
  itest/rust/src/callable_test.rs
  itest/rust/src/codegen_test.rs
  itest/rust/src/object_test.rs
Labels: quality-of-life, c: bind

#343 Fix UB in varcall functions with unit return
  godot-codegen/src/class_generator.rs
  itest/rust/src/node_test.rs
Labels: bug, c: ffi, c: engine

#344 `#[cfg(before_api)]` and `#[cfg(since_api)]`
  godot-bindings/src/lib.rs
  godot-core/src/builtin/basis.rs
  godot-core/src/builtin/transform3d.rs
  godot-core/src/builtin/variant/mod.rs
  godot-core/src/lib.rs
  godot-core/src/obj/gd.rs
  godot-ffi/src/godot_ffi.rs
  itest/rust/Cargo.toml
  itest/rust/build.rs
  itest/rust/src/init_test.rs
Labels: quality-of-life, c: tooling

#346 `GodotClass` is now an unsafe trait; document public API guarantees
  godot-codegen/src/class_generator.rs
  godot-core/src/obj/traits.rs
  godot-macros/src/derive_godot_class/mod.rs
  godot-macros/src/lib.rs
  godot/src/lib.rs
Labels: bug, documentation, c: bind

#355 fix: remove unnecessary `self` from method `from_euler` in quaternion
  godot-core/src/builtin/quaternion.rs
Labels: bug, c: core

#351 Add missing integer vector methods
  godot-core/src/builtin/math/mod.rs
  godot-core/src/builtin/vectors/vector2i.rs
  godot-core/src/builtin/vectors/vector3i.rs
  godot-core/src/builtin/vectors/vector4i.rs
  godot-core/src/builtin/vectors/vector_macros.rs
Labels: feature, c: core

#356 Derive `Hash` for integer Vector types
  godot-core/src/builtin/vectors/vector2i.rs
  godot-core/src/builtin/vectors/vector3i.rs
  godot-core/src/builtin/vectors/vector4i.rs
Labels: feature, c: core

#358 re-introduce TypeStringHint impl for Option<T>
  godot-core/src/property.rs
Labels: bug, c: bind

#362 Refactor `ClassName` and cache class-based StringNames in global table
  .github/composite/rust/action.yml
  .github/other/licenserc.yml
  .github/other/public-docs-token.txt
  .github/other/retry.sh
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  .github/workflows/update-docs.yml
  godot-codegen/Cargo.toml
  godot-codegen/build.rs
  godot-codegen/src/class_generator.rs
  godot-codegen/src/util.rs
  godot-core/src/builtin/array.rs
  godot-core/src/builtin/meta/class_name.rs
  godot-core/src/builtin/meta/mod.rs
  godot-core/src/builtin/string/string_name.rs
  godot-core/src/engine.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/traits.rs
  godot-core/src/registry.rs
  godot-ffi/src/lib.rs
  godot-macros/src/derive_godot_class/mod.rs
  godot-macros/src/derive_godot_class/property.rs
  godot-macros/src/godot_api.rs
  godot-macros/src/method_registration/register_method.rs
  godot-macros/src/util/mod.rs
  itest/rust/Cargo.toml
  itest/rust/src/registration/constant_test.rs
Labels: quality-of-life, c: bind, c: engine

#363 More concise ReadMe/Contribution; smaller code cleanups
  Contributing.md
  ReadMe.md
  godot-codegen/src/central_generator.rs
  godot-core/src/builtin/array.rs
  godot-core/src/builtin/meta/class_name.rs
  godot-core/src/builtin/meta/mod.rs
  godot-core/src/builtin/meta/signature.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/instance_id.rs
  godot-core/src/property.rs
  godot-ffi/src/lib.rs
  itest/rust/build.rs
  itest/rust/src/variant_test.rs
Labels: documentation, quality-of-life, c: core

#364 Dodge-the-Creeps update; code organization in `godot-ffi` crate
  ReadMe.md
  examples/dodge-the-creeps/godot/Hud.tscn
  examples/dodge-the-creeps/godot/Main.tscn
  examples/dodge-the-creeps/godot/Mob.tscn
  examples/dodge-the-creeps/godot/Player.tscn
  examples/dodge-the-creeps/godot/project.godot
  godot-ffi/src/gdextension_plus.rs
  godot-ffi/src/lib.rs
  godot-ffi/src/toolbox.rs
Labels: quality-of-life

#365 No longer run Rust classes inside Godot editor
  .github/workflows/full-ci.yml
  examples/dodge-the-creeps/rust/Cargo.toml
  examples/dodge-the-creeps/rust/src/player.rs
  godot-bindings/Cargo.toml
  godot-codegen/Cargo.toml
  godot-core/Cargo.toml
  godot-core/src/init/mod.rs
  godot-ffi/Cargo.toml
  godot-ffi/src/lib.rs
  godot-macros/Cargo.toml
  godot-macros/src/godot_api.rs
  godot-macros/src/lib.rs
  godot/Cargo.toml
  itest/rust/Cargo.toml
Labels: feature, c: engine
