Repository godot-rust/gdext, pull requests merged in 2023-04, with the labels that each got.

#211 Prebuilt Godot artifacts
  .github/composite/godot-itest/action.yml
  .github/composite/llvm/action.yml
  .github/composite/rust/action.yml
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  Cargo.toml
  godot-bindings/Cargo.toml
  godot-bindings/res/tweak.patch
  godot-bindings/src/godot_exe.rs
  godot-bindings/src/godot_version.rs
  godot-bindings/src/header_gen.rs
  godot-bindings/src/lib.rs
  godot-bindings/src/watch.rs
  godot-codegen/Cargo.toml
  godot-codegen/input/gdextension_interface.h
  godot-codegen/input/tweak.patch
  godot-codegen/src/api_parser.rs
  godot-codegen/src/godot_exe.rs
  godot-codegen/src/lib.rs
  godot-core/Cargo.toml
  godot-core/build.rs
  godot-core/src/builtin/packed_array.rs
  godot-core/src/obj/gd.rs
  godot-core/src/registry.rs
  godot-ffi/Cargo.toml
  godot-ffi/build.rs
  godot-ffi/src/lib.rs
  godot/Cargo.toml
Labels: quality-of-life, c: tooling

#207 Add return values when generating virtual methods
  godot-codegen/src/class_generator.rs
  itest/rust/src/virtual_methods_test.rs
Labels: bug, c: engine

#217 check.sh: find Godot 4 executable when available as `godot`
  check.sh
Labels: quality-of-life, c: tooling

#215 Contribution guidelines, update `.gdextension` configurations
  .github/workflows/full-ci.yml
  Contributing.md
  ReadMe.md
  examples/dodge-the-creeps/godot/DodgeTheCreeps.gdextension
  itest/godot/itest.gdextension
Labels: documentation, c: tooling

#219 Support engine class constants
  godot-codegen/src/api_parser.rs
  godot-codegen/src/class_generator.rs
  godot-codegen/src/util.rs
  itest/rust/src/codegen_test.rs
Labels: feature, c: engine

#216 Catch failed calls to `classdb_get_method_bind()`
  godot-codegen/src/class_generator.rs
Labels: bug, c: engine

#204 Fix various issues with pointer calls
  godot-codegen/src/central_generator.rs
  godot-codegen/src/lib.rs
  godot-codegen/src/util.rs
  godot-core/src/builtin/aabb.rs
  godot-core/src/builtin/array.rs
  godot-core/src/builtin/basis.rs
  godot-core/src/builtin/color.rs
  godot-core/src/builtin/dictionary.rs
  godot-core/src/builtin/macros.rs
  godot-core/src/builtin/meta/mod.rs
  godot-core/src/builtin/meta/signature.rs
  godot-core/src/builtin/node_path.rs
  godot-core/src/builtin/packed_array.rs
  godot-core/src/builtin/plane.rs
  godot-core/src/builtin/projection.rs
  godot-core/src/builtin/quaternion.rs
  godot-core/src/builtin/rect2.rs
  godot-core/src/builtin/rect2i.rs
  godot-core/src/builtin/rid.rs
  godot-core/src/builtin/string.rs
  godot-core/src/builtin/string_name.rs
  godot-core/src/builtin/transform2d.rs
  godot-core/src/builtin/transform3d.rs
  godot-core/src/builtin/variant/impls.rs
  godot-core/src/builtin/variant/mod.rs
  godot-core/src/builtin/vector2.rs
  godot-core/src/builtin/vector2i.rs
  godot-core/src/builtin/vector3.rs
  godot-core/src/builtin/vector3i.rs
  godot-core/src/builtin/vector4.rs
  godot-core/src/builtin/vector4i.rs
  godot-core/src/lib.rs
  godot-core/src/macros.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/instance_id.rs
  godot-core/src/obj/traits.rs
  godot-core/src/registry.rs
  godot-ffi/src/godot_ffi.rs
  godot-ffi/src/lib.rs
  godot-macros/src/derive_godot_class.rs
  itest/godot/InheritTests.gd
  itest/godot/ManualFfiTests.gd
  itest/godot/TestRunner.gd
  itest/godot/TestSuite.gd
  itest/godot/input/GenFfiTests.template.gd
  itest/rust/build.rs
  itest/rust/src/array_test.rs
  itest/rust/src/object_test.rs
  itest/rust/src/projection_test.rs
  itest/rust/src/runner.rs
  itest/rust/src/variant_test.rs
  itest/rust/src/virtual_methods_test.rs
Labels: bug, c: ffi

#218 godot-core: builtin: reimplement Rect2i to reduce need of inner usage
  godot-core/src/builtin/mod.rs
  godot-core/src/builtin/rect2i.rs
  godot-core/src/builtin/transform2d.rs
  godot-core/src/builtin/transform3d.rs
  godot-core/src/builtin/vector2.rs
  godot-core/src/builtin/vector2i.rs
  godot-core/src/builtin/vector3.rs
  godot-core/src/builtin/vector3i.rs
  godot-core/src/builtin/vector4.rs
  godot-core/src/builtin/vector4i.rs
  godot-core/src/builtin/vector_macros.rs
  itest/rust/src/lib.rs
  itest/rust/src/rect2i_test.rs
Labels: quality-of-life, c: core

#224 Impl `Display` for built-ins
  godot-core/src/builtin/aabb.rs
  godot-core/src/builtin/color.rs
  godot-core/src/builtin/plane.rs
  godot-core/src/builtin/projection.rs
  godot-core/src/builtin/rect2.rs
  godot-core/src/builtin/rect2i.rs
  godot-core/src/builtin/rid.rs
  godot-core/src/builtin/transform2d.rs
Labels: feature, c: core

#228 godot-core: bug: fix UB in GodotString::chars_(un)checked
  godot-core/src/builtin/string.rs
  itest/rust/src/string_test.rs
Labels: bug, c: core

#229 Fix `(no base)` showing up in all the docs
  godot-core/src/builtin/array.rs
  godot-core/src/builtin/meta/class_name.rs
  godot-core/src/builtin/meta/mod.rs
Labels: bug, c: bind

#223 Object notification API, `engine` intra-doc links
  godot-codegen/src/central_generator.rs
  godot-codegen/src/class_generator.rs
  godot-codegen/src/context.rs
  godot-codegen/src/lib.rs
  godot-codegen/src/special_cases.rs
  godot-codegen/src/util.rs
  godot-codegen/src/utilities_generator.rs
  godot-core/Cargo.toml
  godot-core/src/lib.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/traits.rs
  godot-core/src/registry.rs
  godot-macros/src/godot_api.rs
  itest/rust/src/object_test.rs
  itest/rust/src/virtual_methods_test.rs
Labels: documentation, feature, c: engine

#231 Add implementation of Callable
  godot-codegen/src/class_generator.rs
  godot-core/src/builtin/callable.rs
  godot-core/src/builtin/macros.rs
  godot-core/src/builtin/mod.rs
  godot-core/src/builtin/others.rs
  godot-core/src/builtin/string_name.rs
  godot-core/src/builtin/variant/impls.rs
  godot-core/src/obj/gd.rs
  itest/rust/src/callable_test.rs
  itest/rust/src/lib.rs
Labels: feature, c: core

#239 Address issues with dodge-the-creeps; use MSRV in CI
  .github/workflows/full-ci.yml
  examples/dodge-the-creeps/godot/.godot/global_script_class_cache.cfg
  examples/dodge-the-creeps/godot/Hud.gd
  examples/dodge-the-creeps/godot/Hud.tscn
  examples/dodge-the-creeps/godot/Main.gd
  examples/dodge-the-creeps/godot/Main.tscn
  examples/dodge-the-creeps/godot/Mob.gd
  examples/dodge-the-creeps/godot/Mob.tscn
  examples/dodge-the-creeps/godot/Player.gd
  examples/dodge-the-creeps/godot/Player.tscn
  examples/dodge-the-creeps/godot/fonts/Xolonium-Regular.tres
  examples/dodge-the-creeps/godot/project.godot
  examples/dodge-the-creeps/rust/src/mob.rs
  examples/dodge-the-creeps/rust/src/player.rs
  godot-bindings/Cargo.toml
  godot-codegen/src/class_generator.rs
  godot-core/Cargo.toml
  godot-ffi/Cargo.toml
  godot-macros/Cargo.toml
Labels: quality-of-life, c: tooling

#234 Fix cast always succeeding due to Godot bug.
  godot-core/src/obj/gd.rs
  itest/rust/src/object_test.rs
Labels: bug, c: engine

#235 panic file and line
  godot-core/src/lib.rs
Labels: quality-of-life, c: core

#244 Update MSRV to 1.66; fix detection in CI
  .github/workflows/full-ci.yml
  godot-bindings/Cargo.toml
  godot-codegen/Cargo.toml
  godot-core/Cargo.toml
  godot-ffi/Cargo.toml
  godot-macros/Cargo.toml
  godot/Cargo.toml
  itest/rust/Cargo.toml
Labels: bug, c: tooling

#250 fix callable crashing when from_sys_init_default is used
  godot-core/src/builtin/callable.rs
  itest/rust/build.rs
Labels: bug, c: ffi

#249 Fix methods always taking a mutable receiver
  godot-core/src/builtin/meta/signature.rs
  godot-core/src/macros.rs
  itest/rust/src/object_test.rs
Labels: bug, c: bind
