Repository godot-rust/gdext, pull requests merged in 2023-10, with the labels that each got.

#396 Allow godot-visible functions to receive a Gd instead of self.
  godot-core/src/obj/base.rs
  godot-core/src/registry.rs
  godot-core/src/storage.rs
  godot-macros/src/class/data_models/field_var.rs
  godot-macros/src/class/data_models/func.rs
  godot-macros/src/class/godot_api.rs
  itest/godot/ManualFfiTests.gd
  itest/rust/src/register_tests/func_test.rs
Labels: feature, c: bind

#439 Fix usage of segmented path attribute with #[func]
  godot-macros/src/class/godot_api.rs
  itest/rust/src/register_tests/constant_test.rs
  itest/rust/src/register_tests/func_test.rs
Labels: bug, c: bind

#419 Allow different class names in rust and Godot
  godot-core/src/registry.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/lib.rs
  itest/rust/src/object_tests/class_rename_test.rs
  itest/rust/src/object_tests/mod.rs
Labels: feature, c: bind

#441 Use the class_name for the field when building PropertyInfo
  godot-core/src/builtin/macros.rs
  godot-macros/src/class/data_models/property.rs
  godot-macros/src/util/list_parser.rs
  godot-macros/src/util/mod.rs
  itest/rust/src/framework/runner.rs
  itest/rust/src/object_tests/property_test.rs
Labels: bug, c: bind

#442 Fix #[func]-like attrs being ignored with macros below them
  godot-macros/src/class/godot_api.rs
  itest/rust/src/register_tests/constant_test.rs
  itest/rust/src/register_tests/func_test.rs
Labels: bug, c: bind

#437 Hot reload support
  godot-core/src/init/mod.rs
  godot-core/src/registry.rs
  godot-macros/Cargo.toml
  godot-macros/build.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/class/godot_api.rs
Labels: feature, c: bind

#448 Remove excessive godot_print-ing for classes loading and unloading
  godot-core/src/registry.rs
Labels: quality-of-life, c: bind

#431 fix vector{2,3} reflect() implementations
  godot-core/src/builtin/vectors/vector2.rs
  godot-core/src/builtin/vectors/vector3.rs
  itest/rust/src/builtin_tests/geometry/vector_test.rs
  itest/rust/src/builtin_tests/mod.rs
Labels: bug, c: core

#443 Allow #[cfg] to be used with #[godot_api] - Part 1: inherent impls
  godot-macros/src/class/data_models/field_var.rs
  godot-macros/src/class/data_models/func.rs
  godot-macros/src/class/godot_api.rs
  godot-macros/src/util/mod.rs
  itest/rust/src/register_tests/constant_test.rs
  itest/rust/src/register_tests/func_test.rs
Labels: bug, c: bind

#449 CI: update LLVM from 10.0 to 15.0.7 -> fix spurious macOS failures
  .github/composite/llvm/action.yml
  godot-bindings/src/godot_exe.rs
Labels: bug, c: tooling

#445 Fix refcount of callables being erroneously decremented when received as argument
  godot-core/src/builtin/callable.rs
  itest/godot/ManualFfiTests.gd
  itest/rust/src/builtin_tests/containers/callable_test.rs
Labels: bug, c: core

#457 `To/FromGodot` has now specific impls for native structs; trait docs
  godot-codegen/src/class_generator.rs
  godot-codegen/src/tests.rs
  godot-codegen/src/util.rs
  godot-core/src/builtin/meta/godot_convert/impls.rs
  godot-core/src/builtin/meta/godot_convert/mod.rs
  godot-core/src/builtin/meta/mod.rs
  godot-core/src/builtin/meta/return_marshal.rs
  godot-macros/src/derive/derive_godot_convert.rs
  godot-macros/src/derive/mod.rs
  godot-macros/src/lib.rs
Labels: documentation, quality-of-life, c: core

#458 Global function tables: `Vec` instead of array, optional lazy loading
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  godot-codegen/Cargo.toml
  godot-codegen/src/central_generator.rs
  godot-codegen/src/class_generator.rs
  godot-codegen/src/util.rs
  godot-core/Cargo.toml
  godot-core/src/builtin/string/string_name.rs
  godot-core/src/init/mod.rs
  godot-core/src/lib.rs
  godot-ffi/Cargo.toml
  godot-ffi/src/gdextension_plus.rs
  godot-ffi/src/lib.rs
  godot-ffi/src/string_cache.rs
  godot-ffi/src/toolbox.rs
  godot/Cargo.toml
  godot/src/lib.rs
  itest/rust/src/builtin_tests/containers/dictionary_test.rs
  itest/rust/src/builtin_tests/containers/rid_test.rs
Labels: feature, c: ffi

#456 Derive default for Plane
  godot-core/src/builtin/plane.rs
Labels: quality-of-life, c: core

#461 Re-enable `ThemeDb` + impl `GodotConvert` for `*mut c_void`
  godot-codegen/src/special_cases.rs
  godot-codegen/src/util.rs
  godot-core/src/builtin/meta/godot_convert/impls.rs
Labels: quality-of-life, c: engine

#465 Fix custom callable no longer working on latest Godot master
  godot-core/Cargo.toml
  godot-core/src/builtin/callable.rs
Labels: quality-of-life, c: core
