Repository godot-rust/gdext, pull requests merged in 2023-11, with the labels that each got.

#454 Bugfix: prevent `Gd` destruction while user object is bound
  Cargo.toml
  godot-core/src/lib.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/guards.rs
  godot-core/src/obj/raw.rs
  godot-core/src/obj/traits.rs
  godot-core/src/storage.rs
  itest/godot/ManualFfiTests.gd
  itest/godot/TestRunner.gd
  itest/rust/src/framework/runner.rs
  itest/rust/src/object_tests/object_test.rs
  itest/rust/src/register_tests/func_test.rs
Labels: bug, c: core, ub

#469 Fixed cyclic build with cargo watch and rust-analyzer for header and json files
  godot-bindings/src/godot_exe.rs
  godot-bindings/src/header_gen.rs
Labels: bug, c: tooling

#471 Split function table constructor into separate methods per class
  godot-codegen/src/central_generator.rs
  godot-codegen/src/codegen_special_cases.rs
  godot-codegen/src/interface_generator.rs
  godot-ffi/src/compat/compat_4_0.rs
Labels: quality-of-life, c: engine

#475 More robust checks against "OpenXR*" classes on macOS
  .github/workflows/update-docs.yml
  godot-codegen/src/special_cases.rs
Labels: bug, c: engine

#476 Rename all virtual traits: `*Virtual` -> `I*`
  examples/dodge-the-creeps/rust/src/hud.rs
  examples/dodge-the-creeps/rust/src/main_scene.rs
  examples/dodge-the-creeps/rust/src/mob.rs
  examples/dodge-the-creeps/rust/src/player.rs
  godot-codegen/src/class_generator.rs
  godot-codegen/src/lib.rs
  godot-core/src/lib.rs
  godot-core/src/registry.rs
  godot-macros/src/lib.rs
  godot-macros/src/util/mod.rs
  godot/src/lib.rs
  itest/rust/src/engine_tests/codegen_test.rs
  itest/rust/src/engine_tests/native_structures_test.rs
  itest/rust/src/object_tests/object_test.rs
  itest/rust/src/object_tests/property_test.rs
  itest/rust/src/object_tests/virtual_methods_test.rs
  itest/rust/src/register_tests/func_test.rs
Labels: quality-of-life, c: engine

#487 Reintroduce `get_` prefixes (revert #477)
  .github/workflows/update-docs.yml
  examples/dodge-the-creeps/rust/src/main_scene.rs
  examples/dodge-the-creeps/rust/src/mob.rs
  examples/dodge-the-creeps/rust/src/player.rs
  godot-codegen/src/api_parser.rs
  godot-codegen/src/class_generator.rs
  godot-codegen/src/special_cases.rs
  godot-core/src/obj/traits.rs
  itest/godot/SpecialTests.gd
  itest/rust/src/builtin_tests/containers/array_test.rs
  itest/rust/src/builtin_tests/containers/callable_test.rs
  itest/rust/src/engine_tests/node_test.rs
  itest/rust/src/object_tests/base_test.rs
  itest/rust/src/object_tests/object_test.rs
  itest/rust/src/object_tests/singleton_test.rs
  itest/rust/src/object_tests/virtual_methods_test.rs
  itest/rust/src/register_tests/constant_test.rs
Labels: quality-of-life, c: engine

#473 Add `GFile`, a wrapper for `FileAccess` implementing `std::io::*` traits
  godot-core/src/builtin/string/gstring.rs
  godot-core/src/engine/gfile.rs
  godot-core/src/engine/mod.rs
  godot/src/lib.rs
  itest/rust/src/engine_tests/file_test.rs
  itest/rust/src/engine_tests/gfile_test.rs
  itest/rust/src/engine_tests/mod.rs
Labels: feature, c: engine

#412 Add a warning when running itest through the editor.
  itest/godot/TestRunner.gd
Labels: quality-of-life, c: tooling

#482 Fixed some missed aligns for 32-bit support
  godot-core/src/builtin/packed_array.rs
  godot-core/src/builtin/string/gstring.rs
Labels: bug, c: ffi, ub

#486 Rework `Gd` constructors, add `default()` to engine classes
  godot-codegen/src/class_generator.rs
  godot-core/src/builtin/string/gstring.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/traits.rs
  godot-core/src/registry.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/class/godot_api.rs
  godot/src/lib.rs
  itest/rust/src/benchmarks/mod.rs
  itest/rust/src/builtin_tests/containers/callable_test.rs
  itest/rust/src/builtin_tests/containers/signal_test.rs
  itest/rust/src/engine_tests/codegen_test.rs
  itest/rust/src/engine_tests/native_structures_test.rs
  itest/rust/src/object_tests/base_test.rs
  itest/rust/src/object_tests/object_test.rs
  itest/rust/src/object_tests/property_template_test.rs
  itest/rust/src/object_tests/property_test.rs
  itest/rust/src/object_tests/virtual_methods_test.rs
  itest/rust/src/register_tests/func_test.rs
Labels: quality-of-life, c: core

#484 Addition of step in export_range
  godot-core/src/property.rs
  godot-macros/src/class/data_models/field_export.rs
  godot-macros/src/util/list_parser.rs
  itest/rust/build.rs
  itest/rust/src/object_tests/property_test.rs
Labels: bug, c: bind

#467 Make `FromGodot` conversions fallible
  godot-codegen/src/class_generator.rs
  godot-codegen/src/util.rs
  godot-core/src/builtin/array.rs
  godot-core/src/builtin/meta/godot_convert/convert_error.rs
  godot-core/src/builtin/meta/godot_convert/impls.rs
  godot-core/src/builtin/meta/godot_convert/mod.rs
  godot-core/src/builtin/meta/mod.rs
  godot-core/src/builtin/meta/return_marshal.rs
  godot-core/src/builtin/meta/signature.rs
  godot-core/src/builtin/string/mod.rs
  godot-core/src/builtin/variant/impls.rs
  godot-core/src/builtin/variant/mod.rs
  godot-core/src/builtin/variant/variant_traits.rs
  godot-core/src/builtin/vectors/vector_axis.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/instance_id.rs
  godot-core/src/obj/raw.rs
  godot-macros/src/class/data_models/func.rs
  godot-macros/src/derive/derive_from_variant.rs
  itest/rust/build.rs
  itest/rust/src/builtin_tests/containers/array_test.rs
  itest/rust/src/builtin_tests/containers/variant_test.rs
  itest/rust/src/builtin_tests/convert_test.rs
  itest/rust/src/builtin_tests/mod.rs
  itest/rust/src/object_tests/object_test.rs
Labels: feature, c: core

#496 Implement `try_get` on `Array`
  godot-core/src/builtin/array.rs
  itest/rust/src/builtin_tests/containers/array_test.rs
Labels: feature, c: core

#493 Enable experimental wasm support
  examples/dodge-the-creeps/godot/DodgeTheCreeps.gdextension
  examples/dodge-the-creeps/rust/.cargo/config
  examples/dodge-the-creeps/rust/Cargo.toml
  examples/dodge-the-creeps/rust/build-wasm.sh
  godot-ffi/Cargo.toml
  godot-ffi/src/compat/compat_4_1.rs
  godot-ffi/src/lib.rs
  godot-ffi/src/plugins.rs
  godot-macros/src/gdextension.rs
  godot/Cargo.toml
  godot/src/lib.rs
Labels: feature

#497 `to_gd()`, `Gd::try_cast()` result, formatting
  .github/bors.toml
  .github/workflows/full-ci.yml
  check.sh
  examples/dodge-the-creeps/rust/src/main_scene.rs
  godot-bindings/src/lib.rs
  godot-codegen/src/util.rs
  godot-core/Cargo.toml
  godot-core/src/builtin/array.rs
  godot-core/src/builtin/callable.rs
  godot-core/src/builtin/meta/godot_convert/convert_error.rs
  godot-core/src/builtin/vectors/vector_axis.rs
  godot-core/src/engine/mod.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/traits.rs
  godot-fmt/Cargo.toml
  godot-fmt/benches/gdext_bench.rs
  godot-fmt/src/lib.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/derive/derive_from_variant.rs
  godot-macros/src/lib.rs
  godot/src/lib.rs
  itest/rust/build.rs
  itest/rust/src/builtin_tests/containers/callable_test.rs
  itest/rust/src/builtin_tests/convert_test.rs
  itest/rust/src/object_tests/base_test.rs
  itest/rust/src/object_tests/object_test.rs
  itest/rust/src/object_tests/property_test.rs
  itest/rust/src/object_tests/virtual_methods_test.rs
  itest/rust/src/register_tests/derive_variant_test.rs
Labels: quality-of-life, c: core

#499 Fixes WithBaseField impl in GodotClass proc macro
  godot-macros/src/class/derive_godot_class.rs
Labels: bug, c: bind

#500 Empty `#[godot_api] impl` blocks are no longer needed
  godot-core/src/lib.rs
  godot-core/src/obj/traits.rs
  godot-core/src/property.rs
  godot-core/src/registry.rs
  godot-macros/src/class/data_models/property.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/class/godot_api.rs
  godot-macros/src/lib.rs
  itest/rust/build.rs
  itest/rust/src/object_tests/object_test.rs
  itest/rust/src/object_tests/property_test.rs
  itest/rust/src/object_tests/virtual_methods_test.rs
  itest/rust/src/register_tests/constant_test.rs
  itest/rust/src/register_tests/option_ffi_test.rs
  itest/rust/src/register_tests/var_test.rs
Labels: quality-of-life, c: bind

#502 `MethodInfo` (`GDExtensionClassMethodInfo`) collides with `GDExtensionMethodInfo`
  godot-core/src/builtin/meta/registration/method.rs
  godot-macros/src/class/data_models/func.rs
Labels: quality-of-life, c: ffi

#504 impl Hash for Gd<T> per instance ID
  godot-core/src/obj/gd.rs
Labels: feature, c: core

#507 Fix packed array tests
  itest/rust/src/builtin_tests/containers/packed_array_test.rs
  itest/rust/src/builtin_tests/mod.rs
Labels: bug

#508 Add serde support for GString, StringName, NodePath and Array
  check.sh
  godot-core/Cargo.toml
  godot-core/src/builtin/array.rs
  godot-core/src/builtin/string/gstring.rs
  godot-core/src/builtin/string/node_path.rs
  godot-core/src/builtin/string/string_name.rs
  itest/rust/Cargo.toml
  itest/rust/src/builtin_tests/mod.rs
  itest/rust/src/builtin_tests/serde_test.rs
Labels: feature, c: core

#509 Fix comments with legacy `TypedArray` to `Array`
  godot-codegen/src/lib.rs
  godot-core/src/builtin/array.rs
  godot-core/src/builtin/variant/mod.rs
Labels: documentation

#512 Check runtime and compiled Godot versions for compatibility
  godot-ffi/src/compat/compat_4_1.rs
Labels: quality-of-life, c: ffi
