Repository godot-rust/gdext, pull requests merged in 2024-02, with the labels that each got.

#589 More robust case conversion; prevent invalid identifiers in codegen
  godot-codegen/src/context.rs
  godot-codegen/src/conv/name_conversions.rs
  godot-codegen/src/generator/classes.rs
  godot-codegen/src/generator/native_structures.rs
  godot-codegen/src/generator/virtual_traits.rs
  godot-codegen/src/lib.rs
  godot-codegen/src/models/domain.rs
  godot-codegen/src/special_cases/codegen_special_cases.rs
  godot-codegen/src/special_cases/special_cases.rs
  godot-codegen/src/tests.rs
Labels: bug, c: engine

#591 Map "Self" to class name in functions.
  godot-macros/src/class/data_models/func.rs
  godot-macros/src/class/godot_api.rs
  godot-macros/src/util/mod.rs
  itest/rust/src/object_tests/object_test.rs
Labels: bug, c: register

#592 Fix question mark lint.
  godot-macros/src/class/data_models/field_export.rs
  godot-macros/src/class/godot_api.rs
  godot-macros/src/util/list_parser.rs
Labels: quality-of-life

#581 Remove usage of `static mut`
  godot-core/Cargo.toml
  godot-core/src/builtin/meta/signature.rs
  godot-core/src/init/mod.rs
  godot-core/src/lib.rs
  godot-ffi/Cargo.toml
  godot-ffi/src/binding/mod.rs
  godot-ffi/src/binding/multi_threaded.rs
  godot-ffi/src/binding/single_threaded.rs
  godot-ffi/src/lib.rs
  godot-ffi/src/toolbox.rs
Labels: quality-of-life, c: ffi

#593 `#[class(no_init)]` to explicitly disable constructor
  godot-core/src/lib.rs
  godot-core/src/registry.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/class/godot_api.rs
  godot-macros/src/lib.rs
  godot-macros/src/util/kv_parser.rs
  godot-macros/src/util/mod.rs
  itest/godot/ManualFfiTests.gd
  itest/godot/TestSuite.gd
  itest/rust/src/builtin_tests/string/string_name_test.rs
  itest/rust/src/object_tests/class_rename_test.rs
  itest/rust/src/object_tests/object_test.rs
  itest/rust/src/object_tests/onready_test.rs
  itest/rust/src/object_tests/property_test.rs
  itest/rust/src/object_tests/virtual_methods_test.rs
  itest/rust/src/register_tests/constant_test.rs
Labels: feature, c: register

#594 godot-core: move some modules into their own files
  godot-core/src/deprecated.rs
  godot-core/src/lib.rs
  godot-core/src/private.rs
  godot-core/src/registry/callbacks.rs
  godot-core/src/registry/mod.rs
  godot-core/src/storage/instance_storage.rs
  godot-core/src/storage/mod.rs
  godot-core/src/storage/multi_threaded.rs
  godot-core/src/storage/single_threaded.rs
  godot-macros/src/class/derive_godot_class.rs
  godot/src/lib.rs
Labels: quality-of-life

#595 Make `Var` use `GodotConvert::Via` to align it with `ToGodot` and `FromGodot`
  godot-core/src/builtin/array.rs
  godot-core/src/builtin/dictionary.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/onready.rs
  godot-core/src/property.rs
  godot-macros/src/class/data_models/field_var.rs
  godot-macros/src/derive/derive_godot_convert.rs
  godot-macros/src/derive/derive_var.rs
  godot-macros/src/lib.rs
  godot-macros/src/util/mod.rs
  itest/rust/src/object_tests/property_test.rs
Labels: quality-of-life, c: register

#598 Fix properties not able to clear from editor
  godot-core/src/builtin/meta/godot_convert/impls.rs
  godot-core/src/builtin/meta/godot_convert/mod.rs
  godot-core/src/builtin/meta/mod.rs
  godot-core/src/builtin/string/node_path.rs
  godot-core/src/obj/gd.rs
  itest/rust/src/builtin_tests/containers/variant_test.rs
Labels: bug, c: register

#596 tr! and tr_n! macros
  godot-core/src/engine/mod.rs
  godot-core/src/engine/translate.rs
  godot-core/src/lib.rs
  itest/rust/src/engine_tests/mod.rs
  itest/rust/src/engine_tests/translate_test.rs
Labels: feature, c: engine

#602 Minor refactor: `godot_api` internals
  godot-codegen/src/conv/name_conversions.rs
  godot-macros/src/class/godot_api.rs
Labels: quality-of-life, c: register

#601 Add Godot's named colors as constants
  .github/workflows/update-docs.yml
  godot-core/src/builtin/color.rs
  godot-core/src/builtin/color_constants.rs
  godot-core/src/builtin/mod.rs
Labels: feature, c: core

#599 Rewrite the derive macros related to `GodotConvert`
  godot-macros/src/derive/data_models/c_style_enum.rs
  godot-macros/src/derive/data_models/godot_attribute.rs
  godot-macros/src/derive/data_models/godot_convert.rs
  godot-macros/src/derive/data_models/mod.rs
  godot-macros/src/derive/data_models/newtype.rs
  godot-macros/src/derive/derive_export.rs
  godot-macros/src/derive/derive_from_godot.rs
  godot-macros/src/derive/derive_from_variant.rs
  godot-macros/src/derive/derive_godot_convert.rs
  godot-macros/src/derive/derive_to_godot.rs
  godot-macros/src/derive/derive_to_variant.rs
  godot-macros/src/derive/derive_var.rs
  godot-macros/src/derive/mod.rs
  godot-macros/src/lib.rs
  godot-macros/src/util/kv_parser.rs
  godot-macros/src/util/mod.rs
  godot/src/lib.rs
  godot/src/prelude.rs
  itest/rust/src/object_tests/property_test.rs
  itest/rust/src/register_tests/derive_variant_test.rs
Labels: feature, c: register

#604 Improve function call diagnostics; fix UB on varcall argument mismatch.
  godot-codegen/src/generator/builtins.rs
  godot-codegen/src/generator/classes.rs
  godot-core/src/builtin/meta/mod.rs
  godot-core/src/builtin/meta/signature.rs
  godot-core/src/engine/mod.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/raw.rs
  godot-core/src/private.rs
  godot-macros/src/class/data_models/func.rs
  itest/rust/src/builtin_tests/containers/callable_test.rs
  itest/rust/src/object_tests/object_test.rs
Labels: bug, c: core, ub

#607 doc: Adjusted `#[signal]` doc with example using parameter.
  godot-macros/src/lib.rs
Labels: documentation, c: register

#606 `#[func(virtual)]`: override virtual Rust functions in GDScript
  godot-bindings/src/godot_exe.rs
  godot-codegen/src/special_cases/codegen_special_cases.rs
  godot-core/src/builtin/meta/registration/method.rs
  godot-core/src/builtin/meta/signature.rs
  godot-core/src/builtin/string/string_name.rs
  godot-core/src/obj/base.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/traits.rs
  godot-core/src/private.rs
  godot-ffi/src/extras.rs
  godot-macros/src/class/data_models/field_var.rs
  godot-macros/src/class/data_models/func.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/class/godot_api.rs
  godot-macros/src/lib.rs
  godot-macros/src/util/mod.rs
  godot/src/lib.rs
  itest/godot/ManualFfiTests.gd
  itest/godot/SpecialTests.gd
  itest/rust/src/register_tests/func_test.rs
  itest/rust/src/register_tests/func_virtual_test.rs
  itest/rust/src/register_tests/mod.rs
Labels: feature, c: register

#609 Fix custom callables panicking when no arguments are passed
  godot-core/src/builtin/variant/mod.rs
  itest/rust/src/builtin_tests/containers/callable_test.rs
Labels: bug, c: ffi

#611 Remove 3 methods from `GDExtension` class, following upstream
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  godot-codegen/src/special_cases/special_cases.rs
Labels: quality-of-life, status: upstream, c: engine

#605 ColorHsv addition
  godot-core/src/builtin/color.rs
  godot-core/src/builtin/color_hsv.rs
  godot-core/src/builtin/mod.rs
  itest/rust/src/benchmarks/color.rs
  itest/rust/src/benchmarks/mod.rs
  itest/rust/src/builtin_tests/color_test.rs
  itest/rust/src/builtin_tests/serde_test.rs
Labels: feature, c: core

#613 Fix `ci-status` job not considering cancellations + 2 other issues
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
Labels: bug, c: tooling

#612 Unregister editor plugins on shutdown
  godot-core/src/registry/mod.rs
  godot-ffi/src/global.rs
Labels: bug, c: register

#614 Remove most `#[deprecated]` symbols
  godot-codegen/src/generator/classes.rs
  godot-codegen/src/generator/enums.rs
  godot-core/src/engine/io/resources.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/traits.rs
  godot-macros/src/class/data_models/field_export.rs
  godot/src/prelude.rs
  itest/rust/src/object_tests/property_test.rs
Labels: quality-of-life

#603 Some cleanup and more accurate tracking of safety invariants
  godot-codegen/src/context.rs
  godot-codegen/src/generator/builtins.rs
  godot-codegen/src/generator/classes.rs
  godot-codegen/src/generator/functions_common.rs
  godot-codegen/src/generator/utility_functions.rs
  godot-codegen/src/generator/virtual_traits.rs
  godot-core/src/builtin/array.rs
  godot-core/src/obj/traits.rs
  godot-macros/src/class/derive_godot_class.rs
  itest/rust/src/builtin_tests/containers/array_test.rs
  itest/rust/src/object_tests/object_test.rs
Labels: bug, c: core, ub

#619 For v4.3+, switch `#[class(tool)]` to use Godot's native "runtime class" feature
  godot-core/src/private.rs
  godot-core/src/registry/mod.rs
  godot-ffi/src/binding/multi_threaded.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/class/godot_api.rs
  godot-macros/src/util/mod.rs
Labels: feature, c: register

#618 Fixing failed CI builds caused by `remove_dir_all` failure
  godot-bindings/src/lib.rs
  godot-core/build.rs
Labels: bug, c: tooling

#622 `ScriptInstance` cleanup + documentation
  godot-codegen/src/generator/docs.rs
  godot-codegen/src/generator/functions_common.rs
  godot-codegen/src/generator/virtual_traits.rs
  godot-codegen/src/special_cases/special_cases.rs
  godot-core/src/engine/script_instance.rs
  itest/rust/src/builtin_tests/script/script_instance_tests.rs
Labels: documentation, quality-of-life, c: engine

#630 Add: Missing functions for Packed*Array
  godot-core/src/builtin/packed_array.rs
Labels: feature, c: core

#632 Add Callable::bindv
  godot-core/src/builtin/callable.rs
  itest/rust/src/builtin_tests/containers/callable_test.rs
Labels: feature, c: core

#634 Add `CallError`, `try_*` varcalls and improve error diagnostics
  godot-codegen/src/generator/central_files.rs
  godot-codegen/src/generator/functions_common.rs
  godot-codegen/src/models/domain.rs
  godot-core/src/builtin/array.rs
  godot-core/src/builtin/meta/call_error.rs
  godot-core/src/builtin/meta/godot_convert/convert_error.rs
  godot-core/src/builtin/meta/mod.rs
  godot-core/src/builtin/meta/signature.rs
  godot-core/src/builtin/variant/impls.rs
  godot-core/src/builtin/variant/mod.rs
  godot-core/src/engine/script_instance.rs
  godot-core/src/log.rs
  godot-core/src/obj/gd.rs
  godot-core/src/private.rs
  godot-core/src/registry/mod.rs
  godot-ffi/src/extras.rs
  godot-ffi/src/godot_ffi.rs
  godot-ffi/src/toolbox.rs
  godot-macros/src/class/data_models/func.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/derive/derive_from_godot.rs
  itest/rust/src/framework/mod.rs
  itest/rust/src/framework/runner.rs
  itest/rust/src/object_tests/dynamic_call_test.rs
  itest/rust/src/object_tests/mod.rs
  itest/rust/src/object_tests/object_test.rs
Labels: feature, c: core, c: engine
