Repository godot-rust/gdext, pull requests merged in 2024-04, with the labels that each got.

#655 Update to ReadMe, lib.rs, doc token
  .github/other/public-docs-token.txt
  ReadMe.md
  examples/hot-reload/godot/test/orchestrate.py
  godot-macros/Cargo.toml
  godot/src/lib.rs
Labels: documentation, quality-of-life, c: tooling

#657 More reliable macOS hot-reloading test, workaround missing GDExtension methods
  .github/composite/godot-install/action.yml
  .github/composite/llvm/action.yml
  .github/workflows/full-ci.yml
  .gitignore
  examples/dodge-the-creeps/godot/.godot/global_script_class_cache.cfg
  examples/hot-reload/godot/.godot/global_script_class_cache.cfg
  examples/hot-reload/godot/test/ReloadOrchestrator.gd
  examples/hot-reload/godot/test/ReloadTest.gd
  examples/hot-reload/godot/test/orchestrate.py
  examples/hot-reload/godot/test/run-test.sh
  examples/hot-reload/rust/src/lib.rs
  godot-codegen/src/special_cases/special_cases.rs
Labels: bug, c: tooling

#650 Store Property / Method list in ScriptInstanceData #647
  godot-core/src/builtin/meta/mod.rs
  godot-core/src/engine/script_instance.rs
  itest/rust/src/builtin_tests/script/script_instance_tests.rs
Labels: bug, c: ffi, c: engine

#644 Add Erased Convert Error Type
  godot-core/src/builtin/array.rs
  godot-core/src/builtin/meta/call_error.rs
  godot-core/src/builtin/meta/godot_convert/convert_error.rs
  godot-core/src/builtin/variant/impls.rs
  godot-core/src/obj/raw.rs
  godot-macros/src/derive/derive_from_godot.rs
  itest/rust/src/builtin_tests/convert_test.rs
Labels: quality-of-life, c: core

#656 Avoid TLS-destructors causing the dynamic library to not be unloaded when hot reloading
  godot-core/src/init/mod.rs
  godot-ffi/Cargo.toml
  godot-ffi/src/binding/single_threaded.rs
  godot-ffi/src/lib.rs
  godot-ffi/src/linux_reload_workaround.rs
  godot-macros/src/gdextension.rs
  godot-macros/src/util/kv_parser.rs
Labels: quality-of-life, c: ffi

#660 Fix objects not getting initialized properly when returned from ffi
  godot-codegen/src/generator/builtins.rs
  godot-codegen/src/generator/classes.rs
  godot-codegen/src/generator/functions_common.rs
  godot-codegen/src/util.rs
  godot-core/src/builtin/callable.rs
  godot-core/src/builtin/meta/mod.rs
  godot-core/src/builtin/meta/return_marshal.rs
  godot-core/src/builtin/meta/signature.rs
  godot-core/src/builtin/plane.rs
  godot-core/src/builtin/rid.rs
  godot-core/src/builtin/signal.rs
  godot-core/src/builtin/variant/mod.rs
  godot-core/src/log.rs
  godot-core/src/obj/raw.rs
  godot-ffi/src/godot_ffi.rs
  itest/rust/src/object_tests/object_test.rs
Labels: bug, c: ffi, ub

#672 CI: job running experimental API should use `custom-godot`
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
Labels: bug, c: tooling

#668 fix `#[var]` docs typo
  godot-cell/src/lib.rs
  godot-codegen/src/generator/classes.rs
  godot-core/src/builtin/array.rs
  godot-ffi/src/lib.rs
  godot-macros/src/class/data_models/func.rs
  godot-macros/src/lib.rs
  itest/godot/SpecialTests.gd
  itest/rust/src/object_tests/enum_test.rs
Labels: documentation, c: register

#666 Sum, Product implementations for Iterator<Vector*>
  godot-core/src/builtin/vectors/vector3.rs
  godot-core/src/builtin/vectors/vector4i.rs
  godot-core/src/builtin/vectors/vector_macros.rs
Labels: feature, c: core

#674 Fix dead link to Objects chapter in book (docs)
  godot-core/src/obj/gd.rs
Labels: documentation

#670 Correctly free property and method lists
  godot-core/src/engine/script_instance.rs
Labels: bug, c: engine

#682 Support macOS arm64 architecture in CI
  .github/composite/godot-itest/action.yml
  .github/composite/llvm/action.yml
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  godot-bindings/Cargo.toml
  godot-bindings/src/header_gen.rs
Labels: feature, c: tooling

#679 Add some missing godot-convert impls for pointers
  godot-core/src/builtin/meta/godot_convert/impls.rs
Labels: bug, c: register

#658 Track ptrcall/varcall in tests; smaller improvements
  .github/workflows/update-docs.yml
  examples/hot-reload/godot/test/run-test.sh
  godot-core/Cargo.toml
  godot-core/src/builtin/meta/mod.rs
  godot-core/src/builtin/meta/signature.rs
  godot-core/src/builtin/variant/impls.rs
  godot-core/src/private.rs
  godot-ffi/Cargo.toml
  godot-ffi/src/toolbox.rs
  godot-macros/src/class/data_models/func.rs
  godot/Cargo.toml
  itest/godot/input/GenFfiTests.template.gd
  itest/rust/Cargo.toml
  itest/rust/build.rs
Labels: quality-of-life

#680 Make servers register at the right level
  godot-codegen/src/special_cases/special_cases.rs
  godot-codegen/src/util.rs
  itest/rust/src/lib.rs
  itest/rust/src/object_tests/init_level_test.rs
  itest/rust/src/object_tests/mod.rs
Labels: bug, c: register

#683 Replace `NodeExt` + `PackedSceneExt` traits with `impl` blocks, extending classes directly
  .github/workflows/full-ci.yml
  godot-codegen/src/generator/classes.rs
  godot-codegen/src/special_cases/special_cases.rs
  godot-core/src/engine/io/resources.rs
  godot-core/src/engine/manual_extensions.rs
  godot-core/src/engine/mod.rs
  godot-core/src/obj/traits.rs
  godot/src/prelude.rs
  itest/rust/src/engine_tests/node_test.rs
Labels: quality-of-life, c: engine
