Repository godot-rust/gdext, pull requests merged in 2024-06, with the labels that each got.

#740 `api-4-x-y` features; automated version sync; `#[cfg]` cleanup.
  .github/composite/godot-itest/action.yml
  .github/other/patch-prebuilt.sh
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  Cargo.toml
  godot-bindings/Cargo.toml
  godot-bindings/src/import.rs
  godot-bindings/src/lib.rs
  godot-cell/Cargo.toml
  godot-codegen/Cargo.toml
  godot-codegen/src/formatter/mod.rs
  godot-core/Cargo.toml
  godot-core/src/tools/script_instance.rs
  godot-ffi/Cargo.toml
  godot-macros/Cargo.toml
  godot/Cargo.toml
  itest/repo-tweak/Cargo.toml
  itest/repo-tweak/src/lib.rs
  itest/repo-tweak/src/main.rs
  itest/rust/Cargo.toml
  itest/rust/build.rs
Labels: quality-of-life, c: tooling

#721 Refactor vector_macros to consistently generate all vector types
  godot-core/src/builtin/aabb.rs
  godot-core/src/builtin/math/float.rs
  godot-core/src/builtin/vectors/vector2.rs
  godot-core/src/builtin/vectors/vector2i.rs
  godot-core/src/builtin/vectors/vector3.rs
  godot-core/src/builtin/vectors/vector3i.rs
  godot-core/src/builtin/vectors/vector4.rs
  godot-core/src/builtin/vectors/vector4i.rs
  godot-core/src/builtin/vectors/vector_macros.rs
  itest/rust/src/builtin_tests/geometry/vector_test.rs
  itest/rust/src/builtin_tests/geometry/vector_test/vector2_test.rs
  itest/rust/src/builtin_tests/geometry/vector_test/vector2i_test.rs
  itest/rust/src/builtin_tests/geometry/vector_test/vector3_test.rs
  itest/rust/src/builtin_tests/geometry/vector_test/vector3i_test.rs
  itest/rust/src/builtin_tests/geometry/vector_test/vector4_test.rs
  itest/rust/src/builtin_tests/geometry/vector_test/vector4i_test.rs
  itest/rust/src/builtin_tests/mod.rs
Labels: quality-of-life, c: core

#736 Block `GdCell::borrow` and `GdCell::borrow_mut` on other threads
  godot-cell/src/blocking_cell.rs
  godot-cell/src/blocking_guards.rs
  godot-cell/src/cell.rs
  godot-cell/src/guards.rs
  godot-cell/src/lib.rs
  godot-cell/tests/mock.rs
  godot-cell/tests/mock/blocking.rs
  godot-cell/tests/mock/main.rs
  godot-cell/tests/mock/panicking.rs
  godot-core/src/obj/guards.rs
  godot-core/src/obj/script.rs
  godot-core/src/storage/instance_storage.rs
  godot-core/src/storage/multi_threaded.rs
  godot-core/src/storage/single_threaded.rs
Labels: bug, c: core

#744 Test `Base<T>` destruction and swapping
  godot-core/src/obj/base.rs
  godot-core/src/obj/gd.rs
  itest/rust/src/object_tests/base_test.rs
Labels: quality-of-life, c: core

#750 Rework the safety invariants of `Global` a bit
  godot-ffi/src/global.rs
Labels: quality-of-life, c: core

#762 Clippy fixes for Rust 1.79
  godot-codegen/src/models/json.rs
  godot-macros/src/class/data_models/field_var.rs
  godot-macros/src/class/data_models/func.rs
  godot-macros/src/class/data_models/inherent_impl.rs
  itest/repo-tweak/src/lib.rs
  itest/rust/src/object_tests/object_swap_test.rs
Labels: quality-of-life, c: tooling

#751 Fix: Consistent by-value and by-ref parameters for geometric types
  godot-core/src/builtin/aabb.rs
  godot-core/src/builtin/basis.rs
  godot-core/src/builtin/plane.rs
  godot-core/src/builtin/rect2.rs
  godot-core/src/builtin/rect2i.rs
  godot-core/src/builtin/transform2d.rs
  godot-core/src/builtin/transform3d.rs
  itest/rust/src/builtin_tests/geometry/basis_test.rs
  itest/rust/src/builtin_tests/geometry/plane_test.rs
  itest/rust/src/builtin_tests/geometry/transform2d_test.rs
  itest/rust/src/builtin_tests/geometry/transform3d_test.rs
Labels: quality-of-life, c: core

#759 Add an engine class bound to `upcast_ref`/`upcast_mut`
  godot-core/src/obj/gd.rs
  godot-core/src/obj/raw.rs
Labels: bug, c: register, ub

#754 Fix native structures exposing `*mut Gd<Object>`, provide accessor
  godot-codegen/src/conv/type_conversions.rs
  godot-codegen/src/generator/native_structures.rs
  godot-core/src/obj/gd.rs
  itest/rust/src/engine_tests/native_structures_test.rs
Labels: bug, c: ffi

#769 Packaging preparations
  .github/other/update-version.sh
  .github/workflows/update-docs.yml
  godot-bindings/Cargo.toml
  godot-bindings/src/lib.rs
  godot-cell/Cargo.toml
  godot-cell/src/lib.rs
  godot-codegen/Cargo.toml
  godot-codegen/src/formatter/mod.rs
  godot-codegen/src/generator/enums.rs
  godot-codegen/src/lib.rs
  godot-core/Cargo.toml
  godot-core/src/builtin/collections/array.rs
  godot-core/src/builtin/collections/packed_array.rs
  godot-core/src/builtin/color.rs
  godot-core/src/builtin/mod.rs
  godot-core/src/builtin/projection.rs
  godot-core/src/deprecated.rs
  godot-core/src/lib.rs
  godot-core/src/obj/gd.rs
  godot-ffi/Cargo.toml
  godot-ffi/src/lib.rs
  godot-macros/Cargo.toml
  godot-macros/src/lib.rs
  godot/Cargo.toml
  godot/src/__docs.rs
  godot/src/lib.rs
  itest/repo-tweak/Cargo.toml
Labels: documentation, c: tooling

#747 Constraint `ITrait` Bound to it's Corresponding Class
  godot-codegen/src/generator/virtual_traits.rs
  godot-macros/src/lib.rs
Labels: bug, c: register

#741 Cleanup some stuff mainly related to script instance
  godot-core/src/builtin/callable.rs
  godot-core/src/builtin/string/string_name.rs
  godot-core/src/builtin/variant/mod.rs
  godot-core/src/meta/mod.rs
  godot-core/src/obj/script.rs
  godot-core/src/registry/callbacks.rs
  godot-core/src/registry/class.rs
  godot-core/src/registry/constant.rs
  godot-ffi/src/conv.rs
  godot-ffi/src/lib.rs
  itest/godot/ManualFfiTests.gd
  itest/rust/src/builtin_tests/script/script_instance_tests.rs
Labels: quality-of-life, c: ffi

#775 Use `Cow<'static, str>`, following prebuilt upstream
  godot-bindings/src/lib.rs
  godot-codegen/src/models/json.rs
Labels: quality-of-life, c: tooling

#777 Packaging preparations II
  .github/composite/godot-itest/action.yml
  .github/other/apply-doc-cfg.sh
  .github/other/update-version.sh
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  .github/workflows/release-version.yml
  examples/hot-reload/godot/test/run-test.sh
  godot-bindings/Cargo.toml
  godot-bindings/src/import.rs
  godot-cell/Cargo.toml
  godot-codegen/Cargo.toml
  godot-core/Cargo.toml
  godot-core/src/obj/gd.rs
  godot-core/src/obj/script.rs
  godot-core/src/obj/traits.rs
  godot-ffi/Cargo.toml
  godot-ffi/src/linux_reload_workaround.rs
  godot-macros/Cargo.toml
  godot/Cargo.toml
  godot/src/lib.rs
  itest/rust/Cargo.toml
Labels: documentation, c: tooling

#761 Add more `normalized` functions
  godot-core/src/builtin/vectors/vector_macros.rs
  itest/rust/src/builtin_tests/geometry/vector_test/vector2_test.rs
  itest/rust/src/builtin_tests/geometry/vector_test/vector3_test.rs
  itest/rust/src/builtin_tests/geometry/vector_test/vector4_test.rs
Labels: feature, c: core

#776 Document why `Basis` columns are `a`, `b`, and `c`
  godot-core/src/builtin/basis.rs
  godot-core/src/builtin/transform2d.rs
  godot-core/src/builtin/transform3d.rs
Labels: documentation, c: core

#773 Reorder compile errors for `#[derive(GodotClass)]`
  godot-macros/src/class/derive_godot_class.rs
Labels: quality-of-life, c: register

#781 Change logic to disable OpenXR for iOS
  godot-codegen/src/special_cases/special_cases.rs
Labels: bug, c: tooling
