Repository godot-rust/gdext, pull requests merged in 2024-07, with the labels that each got.

#785 Added implementation to convert Vec<$Element> into $PackedArray types.
  godot-core/src/builtin/collections/packed_array.rs
  itest/rust/src/builtin_tests/containers/packed_array_test.rs
Labels: feature, c: core

#788 Pointer is already *const u32 on aarch64
  godot-core/src/builtin/string/string_chars.rs
Labels: bug, c: core

#768 Add `snapped` to integer vectors
  godot-core/src/builtin/vectors/vector2i.rs
  godot-core/src/builtin/vectors/vector3i.rs
  godot-core/src/builtin/vectors/vector4i.rs
  godot-core/src/builtin/vectors/vector_macros.rs
  itest/rust/src/builtin_tests/geometry/vector_test/vector2i_test.rs
  itest/rust/src/builtin_tests/geometry/vector_test/vector3i_test.rs
  itest/rust/src/builtin_tests/geometry/vector_test/vector4i_test.rs
Labels: feature, c: core

#770 Add determinant to Transform2D
  .gitignore
  godot-core/src/builtin/transform2d.rs
  itest/rust/src/builtin_tests/geometry/transform2d_test.rs
Labels: feature, c: core

#783 Support `#[export(range = (radians_as_degrees, suffix="XX"))]`
  godot-core/src/deprecated.rs
  godot-core/src/meta/mod.rs
  godot-core/src/registry/property.rs
  godot-macros/src/class/data_models/field_export.rs
  godot-macros/src/util/kv_parser.rs
  godot-macros/src/util/list_parser.rs
  itest/rust/src/object_tests/property_test.rs
Labels: feature, c: register

#794 Add support for nothreads wasm builds (Godot 4.3+)
  godot-bindings/Cargo.toml
  godot-bindings/src/lib.rs
  godot-core/Cargo.toml
  godot-ffi/Cargo.toml
  godot-ffi/build.rs
  godot-ffi/src/binding/single_threaded.rs
  godot/Cargo.toml
  godot/src/lib.rs
Labels: feature, c: wasm

#757 Handle panics in virtual interface methods
  godot-core/src/private.rs
  godot-macros/src/class/data_models/func.rs
  itest/rust/src/object_tests/virtual_methods_test.rs
Labels: bug, c: register

#752 change Global to use Once
  godot-ffi/src/global.rs
Labels: quality-of-life, c: core

#798 Prevent global `CallError` tracker from growing indefinitely
  godot-core/src/private.rs
Labels: quality-of-life, c: core

#799 Add helpful error for renamed Wasm module
  godot-macros/src/gdextension.rs
Labels: quality-of-life, c: wasm

#797 Map `Vector3i.Axis` enum to builtin `Vector3Axis`
  godot-codegen/src/conv/type_conversions.rs
  itest/rust/src/engine_tests/utilities_test.rs
Labels: bug, c: engine

#801 Prevent `out!` from actually formatting the input if disabled
  godot-ffi/src/toolbox.rs
Labels: bug

#774 More thoroughly document `unsafe` in `godot-ffi`
  godot-codegen/src/generator/extension_interface.rs
  godot-codegen/src/generator/method_tables.rs
  godot-core/src/init/mod.rs
  godot-ffi/src/binding/mod.rs
  godot-ffi/src/binding/single_threaded.rs
  godot-ffi/src/compat/compat_4_0.rs
  godot-ffi/src/compat/compat_4_1plus.rs
  godot-ffi/src/compat/mod.rs
  godot-ffi/src/godot_ffi.rs
  godot-ffi/src/lib.rs
  godot-ffi/src/linux_reload_workaround.rs
  godot-ffi/src/string_cache.rs
  godot-ffi/src/toolbox.rs
Labels: quality-of-life, c: register

#780 Disable main_thread_id assertion for Android debug build
  godot-ffi/src/binding/single_threaded.rs
Labels: bug, c: tooling, c: android

#804 Add crates.io ReadMe + docs logo
  ReadMe.md
  godot/Cargo.toml
  godot/crate-readme.md
  godot/src/lib.rs
  misc/assets/asset-licenses.md
  misc/assets/gdext-ferris.png
Labels: documentation

#787 `GdCell::borrow_mut` should block on main thread if shared ref exists
  godot-cell/src/blocking_cell.rs
  godot-cell/tests/mock/blocking.rs
Labels: bug, c: core

#800 `AsObjectArg` trait enabling implicit conversions for object parameters
  examples/dodge-the-creeps/rust/src/main_scene.rs
  godot-codegen/src/conv/type_conversions.rs
  godot-codegen/src/generator/default_parameters.rs
  godot-codegen/src/generator/functions_common.rs
  godot-codegen/src/models/domain.rs
  godot-codegen/src/util.rs
  godot-core/src/builtin/variant/mod.rs
  godot-core/src/meta/sealed.rs
  godot-core/src/meta/traits.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/mod.rs
  godot-core/src/obj/object_arg.rs
  godot-core/src/obj/raw_gd.rs
  godot-ffi/src/extras.rs
  itest/rust/src/engine_tests/node_test.rs
  itest/rust/src/object_tests/mod.rs
  itest/rust/src/object_tests/object_arg_test.rs
  itest/rust/src/object_tests/object_test.rs
  itest/rust/src/object_tests/virtual_methods_test.rs
Labels: feature, c: engine, breaking-change

#748 Generate documentation from doc comments
  godot-core/Cargo.toml
  godot-core/src/docs.rs
  godot-core/src/init/mod.rs
  godot-core/src/lib.rs
  godot-core/src/registry/class.rs
  godot-core/src/registry/plugin.rs
  godot-macros/Cargo.toml
  godot-macros/src/class/data_models/field.rs
  godot-macros/src/class/data_models/inherent_impl.rs
  godot-macros/src/class/data_models/interface_trait_impl.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/docs.rs
  godot-macros/src/docs/markdown_converter.rs
  godot-macros/src/lib.rs
  godot/Cargo.toml
  godot/src/lib.rs
  godot/tests/docs.rs
  godot/tests/docs.xml
Labels: feature, c: register

#808 Remove deprecated symbols from before v0.1
  godot-codegen/Cargo.toml
  godot-codegen/src/generator/builtins.rs
  godot-codegen/src/generator/central_files.rs
  godot-codegen/src/generator/enums.rs
  godot-codegen/src/util.rs
  godot-core/src/builtin/collections/array.rs
  godot-core/src/builtin/collections/packed_array.rs
  godot-core/src/builtin/color.rs
  godot-core/src/builtin/mod.rs
  godot-core/src/builtin/projection.rs
  godot-core/src/builtin/string/string_name.rs
  godot-core/src/deprecated.rs
  godot-core/src/engine.rs
  godot-core/src/lib.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/script.rs
  godot-core/src/tools/gfile.rs
  godot-core/src/tools/save_load.rs
  godot-macros/Cargo.toml
  godot-macros/src/class/data_models/field.rs
  godot-macros/src/class/data_models/field_export.rs
  godot-macros/src/class/derive_godot_class.rs
  godot/src/lib.rs
  itest/rust/Cargo.toml
  itest/rust/build.rs
  itest/rust/src/builtin_tests/string/gstring_test.rs
  itest/rust/src/framework/runner.rs
Labels: quality-of-life, breaking-change

#809 Fix validation for `api-*` mutual exclusivity
  godot-bindings/build.rs
  godot-cell/src/borrow_state.rs
  godot-core/src/lib.rs
  godot/src/lib.rs
Labels: quality-of-life, c: tooling

#819 Include `register-docs` feature in CI
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  godot-core/src/init/mod.rs
  itest/rust/Cargo.toml
  itest/rust/src/register_tests/constant_test.rs
Labels: quality-of-life, c: tooling

#820 Drop support for Godot 4.0
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  Cargo.toml
  godot-bindings/Cargo.toml
  godot-bindings/build.rs
  godot-bindings/src/import.rs
  godot-codegen/src/generator/extension_interface.rs
  godot-core/Cargo.toml
  godot-core/src/builtin/basis.rs
  godot-core/src/builtin/callable.rs
  godot-core/src/builtin/collections/array.rs
  godot-core/src/builtin/signal.rs
  godot-core/src/builtin/string/gstring.rs
  godot-core/src/builtin/string/mod.rs
  godot-core/src/builtin/string/node_path.rs
  godot-core/src/builtin/string/string_chars.rs
  godot-core/src/builtin/string/string_name.rs
  godot-core/src/builtin/transform3d.rs
  godot-core/src/builtin/variant/impls.rs
  godot-core/src/builtin/variant/mod.rs
  godot-core/src/init/mod.rs
  godot-core/src/obj/object_arg.rs
  godot-core/src/obj/raw_gd.rs
  godot-core/src/obj/script.rs
  godot-core/src/registry/class.rs
  godot-ffi/Cargo.toml
  godot-ffi/src/compat/compat_4_0.rs
  godot-ffi/src/compat/compat_4_1plus.rs
  godot-ffi/src/compat/mod.rs
  godot-ffi/src/godot_ffi.rs
  godot-ffi/src/interface_init.rs
  godot-ffi/src/lib.rs
  godot-ffi/src/string_cache.rs
  godot-ffi/src/toolbox.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/gdextension.rs
  godot/Cargo.toml
  itest/godot/SpecialTests.gd
  itest/repo-tweak/src/main.rs
  itest/rust/src/builtin_tests/geometry/transform2d_test.rs
  itest/rust/src/builtin_tests/string/gstring_test.rs
  itest/rust/src/engine_tests/codegen_test.rs
  itest/rust/src/object_tests/object_test.rs
Labels: c: tooling, c: ffi, breaking-change

#807 Add `OnReady::node()` + `#[init(node = "...")]` attribute
  godot-core/src/obj/onready.rs
  godot-core/src/private.rs
  godot-macros/src/class/derive_godot_class.rs
  itest/rust/src/object_tests/onready_test.rs
Labels: feature, c: register, breaking-change

#821 Builtin docs (impl blocks, navigation table, link to Godot)
  godot-core/src/builtin/aabb.rs
  godot-core/src/builtin/basis.rs
  godot-core/src/builtin/callable.rs
  godot-core/src/builtin/collections/array.rs
  godot-core/src/builtin/collections/dictionary.rs
  godot-core/src/builtin/color.rs
  godot-core/src/builtin/plane.rs
  godot-core/src/builtin/projection.rs
  godot-core/src/builtin/quaternion.rs
  godot-core/src/builtin/rect2.rs
  godot-core/src/builtin/rect2i.rs
  godot-core/src/builtin/rid.rs
  godot-core/src/builtin/signal.rs
  godot-core/src/builtin/string/gstring.rs
  godot-core/src/builtin/string/node_path.rs
  godot-core/src/builtin/string/string_name.rs
  godot-core/src/builtin/transform2d.rs
  godot-core/src/builtin/transform3d.rs
  godot-core/src/builtin/variant/mod.rs
  godot-core/src/builtin/vectors/vector2.rs
  godot-core/src/builtin/vectors/vector2i.rs
  godot-core/src/builtin/vectors/vector3.rs
  godot-core/src/builtin/vectors/vector3i.rs
  godot-core/src/builtin/vectors/vector4.rs
  godot-core/src/builtin/vectors/vector4i.rs
  godot-core/src/builtin/vectors/vector_macros.rs
Labels: documentation, c: core

#823 Set null into Godot Engint APIs nullable parameters as default
  godot-codegen/src/conv/type_conversions.rs
Labels: bug, c: engine

#822 Implement the `safe_ident` strategy for virtual call parameter identifier generation
  godot-codegen/src/special_cases/codegen_special_cases.rs
  godot-codegen/src/util.rs
  godot-macros/src/class/data_models/func.rs
  godot-macros/src/util/mod.rs
  itest/rust/src/register_tests/keyword_parameters_test.rs
  itest/rust/src/register_tests/mod.rs
Labels: bug, c: register

#824 Vector conversion functions
  godot-core/src/builtin/rect2.rs
  godot-core/src/builtin/rect2i.rs
  godot-core/src/builtin/vectors/vector2.rs
  godot-core/src/builtin/vectors/vector2i.rs
  godot-core/src/builtin/vectors/vector3.rs
  godot-core/src/builtin/vectors/vector3i.rs
  godot-core/src/builtin/vectors/vector4.rs
  godot-core/src/builtin/vectors/vector4i.rs
  godot-core/src/builtin/vectors/vector_macros.rs
Labels: feature, c: core
