Repository godot-rust/gdext, pull requests merged in 2024-03, with the labels that each got.

#635 Update to venial API changes
  .github/other/deny.toml
  godot-macros/Cargo.toml
  godot-macros/src/bench.rs
  godot-macros/src/class/data_models/field.rs
  godot-macros/src/class/data_models/func.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/class/godot_api.rs
  godot-macros/src/derive/data_models/c_style_enum.rs
  godot-macros/src/derive/data_models/godot_attribute.rs
  godot-macros/src/derive/data_models/godot_convert.rs
  godot-macros/src/derive/data_models/newtype.rs
  godot-macros/src/derive/derive_export.rs
  godot-macros/src/derive/derive_godot_convert.rs
  godot-macros/src/derive/derive_var.rs
  godot-macros/src/gdextension.rs
  godot-macros/src/itest.rs
  godot-macros/src/lib.rs
  godot-macros/src/util/kv_parser.rs
  godot-macros/src/util/mod.rs
  itest/godot/SpecialTests.gd
Labels: quality-of-life, c: register

#636 Fix: Ensure class servers methods are loaded after hot reload
  godot-core/src/init/mod.rs
Labels: bug, c: ffi

#638 Added godot_print_rich! in log.rs
  godot-core/src/log.rs
Labels: feature, c: engine

#639 fix: OpenXR is not available on iOS
  godot-codegen/src/special_cases/special_cases.rs
Labels: bug, c: engine

#646 Fix packed array exports
  godot-core/src/builtin/packed_array.rs
  godot-core/src/property.rs
Labels: bug, c: register

#645 `ConvertError`: add back default, new constructor with message
  godot-core/src/builtin/array.rs
  godot-core/src/builtin/meta/godot_convert/convert_error.rs
Labels: bug, c: core

#651 MSRV 1.77.1 + several supply chain issues
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  .github/workflows/update-docs.yml
  examples/dodge-the-creeps/rust/Cargo.toml
  godot-bindings/Cargo.toml
  godot-cell/Cargo.toml
  godot-codegen/Cargo.toml
  godot-core/Cargo.toml
  godot-ffi/Cargo.toml
  godot-macros/Cargo.toml
  godot/Cargo.toml
  itest/rust/Cargo.toml
Labels: quality-of-life, c: tooling

#625 Experimental refactoring of `GodotFfi`
  godot-codegen/src/generator/builtins.rs
  godot-core/src/builtin/array.rs
  godot-core/src/builtin/callable.rs
  godot-core/src/builtin/dictionary.rs
  godot-core/src/builtin/macros.rs
  godot-core/src/builtin/meta/class_name.rs
  godot-core/src/builtin/meta/mod.rs
  godot-core/src/builtin/meta/registration/method.rs
  godot-core/src/builtin/meta/return_marshal.rs
  godot-core/src/builtin/meta/signature.rs
  godot-core/src/builtin/packed_array.rs
  godot-core/src/builtin/plane.rs
  godot-core/src/builtin/rid.rs
  godot-core/src/builtin/signal.rs
  godot-core/src/builtin/string/gstring.rs
  godot-core/src/builtin/string/node_path.rs
  godot-core/src/builtin/string/string_name.rs
  godot-core/src/builtin/variant/impls.rs
  godot-core/src/builtin/variant/mod.rs
  godot-core/src/engine/script_instance.rs
  godot-core/src/init/mod.rs
  godot-core/src/log.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/raw.rs
  godot-core/src/registry/callbacks.rs
  godot-ffi/src/extras.rs
  godot-ffi/src/godot_ffi.rs
  godot-ffi/src/lib.rs
  godot-ffi/src/toolbox.rs
  godot-macros/src/class/godot_api.rs
  itest/rust/src/builtin_tests/containers/variant_test.rs
  itest/rust/src/object_tests/object_test.rs
  itest/rust/src/register_tests/option_ffi_test.rs
Labels: quality-of-life, c: ffi

#653 Fix hot-reload panic on Linux
  .github/composite/godot-itest/action.yml
  .github/other/check-example.sh
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  Cargo.toml
  examples/hot-reload/godot/.godot/extension_list.cfg
  examples/hot-reload/godot/.godot/global_script_class_cache.cfg
  examples/hot-reload/godot/MainScene.tscn
  examples/hot-reload/godot/project.godot
  examples/hot-reload/godot/rust.gdextension
  examples/hot-reload/godot/test/MainScene.tscn
  examples/hot-reload/godot/test/ReloadTest.gd
  examples/hot-reload/godot/test/editor_layout.cfg
  examples/hot-reload/godot/test/orchestrate.py
  examples/hot-reload/godot/test/run-test.sh
  examples/hot-reload/rust/Cargo.toml
  examples/hot-reload/rust/src/lib.rs
  godot-core/src/init/mod.rs
  godot-core/src/registry/mod.rs
  godot-ffi/src/binding/mod.rs
  godot-ffi/src/binding/multi_threaded.rs
  godot-ffi/src/binding/single_threaded.rs
  godot-ffi/src/lib.rs
  godot-ffi/src/toolbox.rs
Labels: bug, c: tooling, c: ffi, c: examples

#652 Replace `StringName::from_latin1_with_nul` with a `From<CStr>` conversion
  godot-codegen/src/util.rs
  godot-core/src/builtin/string/gstring.rs
  godot-core/src/builtin/string/node_path.rs
  godot-core/src/builtin/string/string_name.rs
  itest/rust/src/builtin_tests/string/gstring_test.rs
  itest/rust/src/builtin_tests/string/node_path_test.rs
  itest/rust/src/builtin_tests/string/string_name_test.rs
Labels: quality-of-life, c: core
