Repository godot-rust/gdext, pull requests merged in 2024-10, with the labels that each got.

#918 Display script-virtual methods as `_method` instead of `method` in Godot docs
  godot-macros/src/class/data_models/field_var.rs
  godot-macros/src/class/data_models/func.rs
  godot-macros/src/class/data_models/inherent_impl.rs
  godot-macros/src/class/data_models/rpc.rs
  godot-macros/src/docs.rs
Labels: bug, c: register

#929 ReadMe update + clippy error
  ReadMe.md
  itest/rust/src/framework/runner.rs
Labels: documentation

#928 Derive `Ord` and `PartialOrd` for `ClassName`
  godot-core/src/meta/class_name.rs
Labels: feature, c: core

#931 Fix `enum_test.rs` accidentally excluded from itest
  itest/rust/src/object_tests/enum_test.rs
  itest/rust/src/object_tests/mod.rs
Labels: bug, c: tooling
