Repository godot-rust/gdext, pull requests merged in 2025-08, with the labels that each got.

#1258 Add extra class docs for `ResourceFormatLoader` to mention that the `experimental-threads` feature is required
  godot-codegen/src/special_cases/special_cases.rs
Labels: documentation, c: engine, c: threads

#1255 Implement `Gd::try_dynify`.
  godot-core/src/obj/dyn_gd.rs
  godot-core/src/obj/gd.rs
  godot-core/src/registry/class.rs
  itest/rust/src/object_tests/dyn_gd_test.rs
Labels: feature, c: core

#1261 Add PhantomVar<T> to support properties without a backing field
  godot-core/src/registry/property/mod.rs
  godot-core/src/registry/property/phantom_var.rs
  godot-macros/src/class/data_models/field.rs
  godot-macros/src/class/data_models/field_var.rs
  godot-macros/src/class/data_models/property.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/lib.rs
  godot/src/prelude.rs
  itest/godot/ManualFfiTests.gd
  itest/rust/src/object_tests/mod.rs
  itest/rust/src/object_tests/phantom_var_test.rs
Labels: feature, c: register

#1268 Clarify + test `Packed*Array` behavior w.r.t. copy-and-write + `#[var]`
  godot-core/src/builtin/collections/packed_array.rs
  itest/rust/src/object_tests/property_test.rs
Labels: documentation, c: core

#1211 Emit `POSTINITIALIZE` notification after `init()`
  godot-core/src/builtin/string/gstring.rs
  godot-core/src/classes/class_runtime.rs
  godot-core/src/obj/base.rs
  godot-core/src/obj/bounds.rs
  godot-core/src/obj/gd.rs
  godot-core/src/registry/callbacks.rs
  godot-ffi/src/lib.rs
  itest/rust/src/object_tests/base_init_test.rs
  itest/rust/src/object_tests/virtual_methods_test.rs
Labels: feature, c: register

#1282 Allow to use `#[func(gd_self)]` with Interface methods.
  godot-core/src/obj/traits.rs
  godot-core/src/private.rs
  godot-core/src/registry/callbacks.rs
  godot-core/src/storage/instance_storage.rs
  godot-macros/src/class/data_models/func.rs
  godot-macros/src/class/data_models/inherent_impl.rs
  godot-macros/src/class/data_models/interface_trait_impl.rs
  godot-macros/src/lib.rs
  godot-macros/src/util/mod.rs
  itest/rust/src/object_tests/onready_test.rs
  itest/rust/src/object_tests/virtual_methods_test.rs
Labels: feature, c: register

#1283 Fix `ThreadConfined<T>` using thread-unsafe `Drop`
  godot-core/src/obj/gd.rs
  godot-core/src/task/futures.rs
  itest/rust/src/engine_tests/async_test.rs
Labels: bug, ub, c: threads

#1291 Generic `PackedArray<T>`
  godot-core/src/builtin/collections/array.rs
  godot-core/src/builtin/collections/dictionary.rs
  godot-core/src/builtin/collections/extend_buffer.rs
  godot-core/src/builtin/collections/mod.rs
  godot-core/src/builtin/collections/packed_array.rs
  godot-core/src/builtin/collections/packed_array_element.rs
  godot-core/src/builtin/mod.rs
  godot-core/src/builtin/variant/impls.rs
  godot-core/src/builtin/variant/mod.rs
  godot-core/src/meta/args/as_arg.rs
  godot-core/src/meta/args/cow_arg.rs
  godot-core/src/meta/sealed.rs
  godot-core/src/meta/traits.rs
  godot-core/src/registry/property/mod.rs
  godot/src/__docs.rs
  itest/rust/src/builtin_tests/containers/packed_array_test.rs
  itest/rust/src/builtin_tests/containers/variant_test.rs
Labels: feature, c: core
