Repository godot-rust/gdext, pull requests merged in 2025-04, with the labels that each got.

#1115 post `Rust 1.86` update: apply clippy lints
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  .github/workflows/release-version.yml
  check.sh
  godot-bindings/src/import.rs
  godot-core/src/obj/on_ready.rs
  itest/repo-tweak/src/main.rs
  itest/rust/build.rs
Labels: quality-of-life, c: tooling

#1122 Impl dynamic send for `Array<T>`
  godot-core/src/builtin/variant/impls.rs
  itest/rust/src/engine_tests/async_test.rs
Labels: quality-of-life, c: async

#1127 Centralize + update dependencies in workspace `Cargo.toml`
  .github/composite/godot-install/action.yml
  Cargo.toml
  godot-bindings/Cargo.toml
  godot-bindings/src/header_gen.rs
  godot-cell/Cargo.toml
  godot-codegen/Cargo.toml
  godot-core/Cargo.toml
  godot-ffi/Cargo.toml
  godot-macros/Cargo.toml
  itest/rust/Cargo.toml
  itest/rust/src/engine_tests/async_test.rs
Labels: quality-of-life, c: tooling

#1134 Inherited typed signals
  godot-codegen/src/context.rs
  godot-codegen/src/generator/classes.rs
  godot-codegen/src/generator/signals.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/traits.rs
  godot-core/src/private.rs
  godot-core/src/registry/mod.rs
  godot-core/src/registry/signal/mod.rs
  godot-core/src/registry/signal/signal_object.rs
  godot-core/src/registry/signal/typed_signal.rs
  godot-macros/src/class/data_models/inherent_impl.rs
  godot-macros/src/class/data_models/signal.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/util/mod.rs
  godot/src/lib.rs
  itest/rust/src/builtin_tests/containers/signal_test.rs
Labels: feature, c: register

#1135 `emit()` now available on inherited symbols + smaller cleanups
  godot-codegen/src/generator/signals.rs
  godot-core/src/registry/signal/typed_signal.rs
  godot-macros/src/class/data_models/signal.rs
  itest/rust/src/builtin_tests/containers/signal_test.rs
Labels: quality-of-life, c: register

#1137 Prevent signal_future_send_arg_no_panic test from panicing
  godot-core/src/task/futures.rs
  itest/rust/src/engine_tests/async_test.rs
Labels: bug, c: async

#1138 Fix crash related to adding EditorPlugin to the editor before all the classes are registered.
  godot-core/src/registry/class.rs
Labels: bug, c: register

#1143 Release job in minimal CI; temporarily work around Godot blocker
  .github/composite/godot-install/action.yml
  .github/workflows/minimal-ci.yml
Labels: quality-of-life, c: tooling

#1042 Experiment with splitting up signature differently
  godot-codegen/src/generator/builtins.rs
  godot-codegen/src/generator/classes.rs
  godot-codegen/src/generator/functions_common.rs
  godot-codegen/src/generator/utility_functions.rs
  godot-codegen/src/util.rs
  godot-core/src/meta/godot_convert/mod.rs
  godot-core/src/meta/mod.rs
  godot-core/src/meta/param_tuple.rs
  godot-core/src/meta/param_tuple/impls.rs
  godot-core/src/meta/signature.rs
  godot-core/src/registry/method.rs
  godot-core/src/registry/signal/connect_builder.rs
  godot-core/src/registry/signal/typed_signal.rs
  godot-core/src/registry/signal/variadic.rs
  godot-core/src/task/futures.rs
  godot-macros/src/class/data_models/func.rs
  godot-macros/src/class/data_models/inherent_impl.rs
  godot-macros/src/class/data_models/signal.rs
  godot-macros/src/util/mod.rs
Labels: quality-of-life, c: ffi

#1140 Propagate panics in object constructors to `Gd::from_init_fn()`, `new_gd()`, `new_alloc()`
  godot-codegen/src/models/json.rs
  godot-codegen/src/special_cases/special_cases.rs
  godot-core/src/meta/error/call_error.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/traits.rs
  godot-core/src/private.rs
  godot-core/src/registry/callbacks.rs
  itest/godot/ManualFfiTests.gd
  itest/rust/src/register_tests/func_test.rs
Labels: quality-of-life, c: core, c: ffi

#1145 Properly set GDExtensionBool is_valid to true in `to_string` function.
  .github/composite/godot-install/action.yml
  godot-core/src/registry/callbacks.rs
Labels: bug, c: ffi, ub

#1146 User classes expose typed-signal API even without `#[signal]`
  godot-core/src/obj/gd.rs
  godot-macros/src/class/data_models/inherent_impl.rs
  godot-macros/src/class/data_models/signal.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/class/godot_api.rs
  godot-macros/src/util/kv_parser.rs
  godot-macros/src/util/mod.rs
  itest/rust/src/builtin_tests/containers/signal_test.rs
  itest/rust/src/object_tests/object_test.rs
Labels: quality-of-life, c: core
