Repository godot-rust/gdext, pull requests merged in 2025-05, with the labels that each got.

#1142 Document `DynGd<_, D>` type inference.
  godot-core/src/obj/dyn_gd.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/guards.rs
  godot-core/src/obj/traits.rs
  godot-core/src/registry/callbacks.rs
  itest/rust/src/object_tests/dyn_gd_test.rs
Labels: documentation, c: core

#1150 Generated `emit()` functions now take `impl AsArg<T>`
  godot-core/src/builtin/collections/array.rs
  godot-core/src/meta/args/as_arg.rs
  godot-core/src/meta/mod.rs
  godot-core/src/obj/dyn_gd.rs
  godot-core/src/obj/gd.rs
  godot-macros/src/class/data_models/signal.rs
  itest/rust/src/builtin_tests/containers/array_test.rs
  itest/rust/src/builtin_tests/containers/signal_test.rs
  itest/rust/src/engine_tests/async_test.rs
  itest/rust/src/object_tests/dyn_gd_test.rs
  itest/rust/src/object_tests/object_test.rs
Labels: quality-of-life, c: core

#1153 Adjust test to account for `Node::set_name()` change (`String` -> `StringName`)
  itest/rust/src/object_tests/dynamic_call_test.rs
  itest/rust/src/object_tests/object_test.rs
Labels: quality-of-life, c: tooling

#1154 Refactor parsing of `#[godot_api]` inner attributes
  godot-macros/src/class/data_models/inherent_impl.rs
  godot-macros/src/util/mod.rs
Labels: quality-of-life, c: register

#1155 `#[derive(GodotClass)]`, `#[godot_api]` docs: replace table of contents with sidebar
  godot-macros/src/lib.rs
Labels: documentation

#1149 Make CollisionShapes `...debug_color` methods available in release builds.
  godot-codegen/src/special_cases/special_cases.rs
Labels: quality-of-life, c: engine

#1162 Final and non-instantiable classes
  godot-codegen/src/context.rs
  godot-codegen/src/generator/classes.rs
  godot-codegen/src/generator/notifications.rs
  godot-codegen/src/models/domain.rs
  godot-codegen/src/models/domain_mapping.rs
  godot-codegen/src/special_cases/special_cases.rs
  godot-macros/src/class/derive_godot_class.rs
Labels: feature, c: engine, breaking-change

#1167 Decrease `CallError` size from 176 to 8 bytes
  godot-core/src/meta/error/call_error.rs
  godot-core/src/tools/gfile.rs
Labels: c: core, performance

#1152 Signal API improvements
  godot-codegen/src/generator/signals.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/traits.rs
  godot-core/src/registry/signal/connect_builder.rs
  godot-core/src/registry/signal/godot_deref.rs
  godot-core/src/registry/signal/mod.rs
  godot-core/src/registry/signal/typed_signal.rs
  godot-core/src/registry/signal/variadic.rs
  godot-macros/src/class/data_models/signal.rs
  itest/rust/src/builtin_tests/containers/signal_test.rs
  itest/rust/src/engine_tests/async_test.rs
Labels: quality-of-life, c: core

#1171 Clean up `ConnectBuilder` and some other signal APIs
  godot-core/src/meta/args/as_arg.rs
  godot-core/src/meta/mod.rs
  godot-core/src/meta/uniform_object_deref.rs
  godot-core/src/registry/signal/connect_builder.rs
  godot-core/src/registry/signal/godot_deref.rs
  godot-core/src/registry/signal/mod.rs
  godot-core/src/registry/signal/typed_signal.rs
  itest/rust/src/builtin_tests/containers/signal_test.rs
Labels: quality-of-life, c: core

#1168 Document runtime class in editor requirement
  godot-core/src/classes/class_runtime.rs
  godot-core/src/obj/raw_gd.rs
  godot-macros/src/lib.rs
Labels: documentation, c: core

#1179 Replace macro approach with `IndirectSignalReceiver` to force type inference to work when connecting closures to the signals
  godot-core/src/registry/signal/connect_builder.rs
  godot-core/src/registry/signal/mod.rs
  godot-core/src/registry/signal/signal_receiver.rs
  godot-core/src/registry/signal/typed_signal.rs
Labels: quality-of-life, c: core, hard

#1182 Final classes no longer have a `I*` interface trait
  godot-codegen/src/context.rs
  godot-codegen/src/generator/classes.rs
  godot-codegen/src/generator/docs.rs
  godot-codegen/src/generator/virtual_traits.rs
  godot-codegen/src/models/domain.rs
  godot-codegen/src/models/domain_mapping.rs
  godot-codegen/src/special_cases/special_cases.rs
Labels: documentation, feature, c: engine, breaking-change

#1184 Improve signal/async docs; MSRV 1.85 -> 1.87
  .github/workflows/full-ci.yml
  .github/workflows/update-docs.yml
  Changelog.md
  godot-bindings/Cargo.toml
  godot-cell/Cargo.toml
  godot-codegen/Cargo.toml
  godot-core/Cargo.toml
  godot-core/src/builtin/collections/packed_array.rs
  godot-core/src/builtin/real.rs
  godot-core/src/builtin/signal.rs
  godot-core/src/builtin/string/gstring.rs
  godot-core/src/builtin/string/string_name.rs
  godot-core/src/obj/traits.rs
  godot-core/src/registry/signal/signal_receiver.rs
  godot-core/src/registry/signal/typed_signal.rs
  godot-core/src/task/async_runtime.rs
  godot-core/src/task/futures.rs
  godot-ffi/Cargo.toml
  godot-macros/Cargo.toml
  godot-macros/src/lib.rs
  godot/Cargo.toml
  itest/hot-reload/rust/Cargo.toml
  itest/repo-tweak/Cargo.toml
  itest/rust/Cargo.toml
  itest/rust/src/engine_tests/async_test.rs
Labels: documentation, quality-of-life

#1166 Support `@export_file`, `@export_dir` etc. for `Array<GString>` and `PackedStringArray`
  .github/workflows/release-version.yml
  godot-bindings/src/lib.rs
  godot-core/src/meta/property_info.rs
  godot-core/src/meta/traits.rs
  godot-core/src/registry/property.rs
  godot-macros/src/class/data_models/field_export.rs
  godot-macros/src/class/data_models/property.rs
  itest/rust/build.rs
  itest/rust/src/object_tests/property_template_test.rs
Labels: feature, c: register
