Repository godot-rust/gdext, pull requests merged in 2025-01, with the labels that each got.

#995 Fix nightly compiler warnings about `#[cfg(before_api = "4.3")]` in the generated `#[godot_api]` impl
  examples/dodge-the-creeps/rust/src/main_scene.rs
  godot-macros/src/class/data_models/interface_trait_impl.rs
Labels: bug, c: register

#991 Godot FFI: postinit create, compat virtual methods, icon paths
  godot-codegen/src/context.rs
  godot-codegen/src/generator/functions_common.rs
  godot-codegen/src/generator/method_tables.rs
  godot-codegen/src/generator/mod.rs
  godot-codegen/src/generator/utility_functions.rs
  godot-codegen/src/generator/virtual_hashes.rs
  godot-codegen/src/models/domain.rs
  godot-codegen/src/models/domain_mapping.rs
  godot-core/src/obj/bounds.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/traits.rs
  godot-core/src/registry/callbacks.rs
  godot-core/src/registry/class.rs
  godot-core/src/registry/plugin.rs
  godot-ffi/src/lib.rs
  godot-ffi/src/toolbox.rs
  godot-macros/src/class/data_models/func.rs
  godot-macros/src/class/data_models/interface_trait_impl.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/util/mod.rs
Labels: feature, status: upstream, c: ffi

#1010 Follow clippy 1.84; limit `NodePath::subpath()` polyfill again
  godot-codegen/src/special_cases/codegen_special_cases.rs
  godot-core/src/builtin/string/node_path.rs
  godot-core/src/builtin/variant/mod.rs
  godot-core/src/meta/args/ref_arg.rs
  godot-core/src/obj/bounds.rs
  godot-core/src/obj/raw_gd.rs
  godot-ffi/src/toolbox.rs
  godot-macros/src/util/mod.rs
  itest/rust/src/framework/runner.rs
Labels: quality-of-life, c: core

#1007 Re-integrate virtual compat methods
  godot-codegen/src/models/domain_mapping.rs
  godot-core/src/registry/callbacks.rs
  godot-core/src/registry/class.rs
Labels: feature, status: upstream, c: ffi

#999 Document builtin API design
  godot-core/src/builtin/mod.rs
Labels: documentation, c: core

#1011 Fix `#[derive(Var)]` generating incorrect `hint_string` for enums
  godot-macros/src/derive/data_models/c_style_enum.rs
  godot-macros/src/derive/derive_var.rs
  itest/rust/src/object_tests/property_test.rs
Labels: bug, c: register

#1012 Map `Vector2.Axis` and `Vector2i.Axis` to `Vector2Axis`
  godot-codegen/src/conv/type_conversions.rs
Labels: feature, c: engine

#998 Implement `Var` and `Export` for `DynGd<T, D>`
  godot-core/src/obj/dyn_gd.rs
  godot-core/src/registry/class.rs
  godot-ffi/src/toolbox.rs
  itest/godot/ManualFfiTests.gd
  itest/rust/src/object_tests/dyn_gd_test.rs
Labels: feature, c: register

#1014 Remove dead binding code regarding Godot 4.0
  godot-bindings/src/godot_exe.rs
Labels: quality-of-life, c: ffi

#1001 API consistency for bounding boxes
  godot-core/src/builtin/aabb.rs
  godot-core/src/builtin/rect2.rs
  godot-core/src/builtin/rect2i.rs
  itest/rust/src/builtin_tests/geometry/rect2_test.rs
  itest/rust/src/builtin_tests/geometry/rect2i_test.rs
Labels: feature, quality-of-life, c: core

#1003 Document and refactor `PluginItem` related stuff
  godot-core/src/builder/mod.rs
  godot-core/src/docs.rs
  godot-core/src/private.rs
  godot-core/src/registry/callbacks.rs
  godot-core/src/registry/class.rs
  godot-core/src/registry/plugin.rs
  godot-macros/src/class/data_models/inherent_impl.rs
  godot-macros/src/class/data_models/interface_trait_impl.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/class/godot_dyn.rs
  godot-macros/src/docs.rs
  itest/rust/src/register_tests/constant_test.rs
Labels: quality-of-life, c: register

#1022 Support associated types in `#[godot_dyn]`
  godot-macros/src/class/godot_dyn.rs
  itest/rust/src/object_tests/dyn_gd_test.rs
Labels: feature, c: register
