Repository godot-rust/gdext, pull requests merged in 2025-02, with the labels that each got.

#1017 feat: support additional doc comment markdown
  godot-macros/src/docs.rs
  godot-macros/src/docs/markdown_converter.rs
  itest/rust/src/register_tests/register_docs_test.rs
  itest/rust/src/register_tests/res/registered_docs.xml
Labels: feature, c: register

#1008 Test generation of proc-macro code via declarative macro
  .github/other/public-docs-token.txt
  godot-macros/Cargo.toml
  itest/rust/src/engine_tests/codegen_test.rs
Labels: quality-of-life, c: register

#1020 Disambiguate virtual method calls
  godot-macros/src/class/data_models/field_var.rs
  godot-macros/src/class/data_models/func.rs
  godot-macros/src/class/data_models/inherent_impl.rs
  godot-macros/src/class/data_models/interface_trait_impl.rs
  godot-macros/src/class/derive_godot_class.rs
  itest/rust/src/engine_tests/codegen_test.rs
Labels: bug, c: register

#1032 `#[signal]`: validate that there is no function body
  godot-macros/src/class/data_models/inherent_impl.rs
Labels: bug, c: register

#1013 Provide safe way for implementing `IScriptExtension::instance_has`
  godot-codegen/src/special_cases/codegen_special_cases.rs
  godot-core/src/obj/script.rs
  itest/godot/ScriptInstanceTests.gd
  itest/rust/src/builtin_tests/script/script_instance_tests.rs
Labels: feature, c: engine

#1019 in `#[var]s`, handle renamed `#[func]`s
  godot-macros/src/class/data_models/field_var.rs
  godot-macros/src/class/data_models/inherent_impl.rs
  godot-macros/src/class/data_models/property.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/class/godot_api.rs
  godot-macros/src/util/mod.rs
  itest/godot/ManualFfiTests.gd
  itest/rust/src/object_tests/object_test.rs
  itest/rust/src/object_tests/property_test.rs
  itest/rust/src/register_tests/func_test.rs
Labels: bug, c: register

#1016 test: support switching API versions in check.sh
  check.sh
Labels: quality-of-life, c: tooling

#1015 fix: parse doc strings with litrs
  godot-macros/Cargo.toml
  godot-macros/src/docs.rs
  itest/rust/src/register_tests/res/registered_docs.xml
Labels: bug, c: register

#1033 Fix `Variant` -> `Gd` conversions not taking into account dead objects
  godot-codegen/src/generator/central_files.rs
  godot-core/src/builtin/variant/mod.rs
  godot-core/src/meta/error/convert_error.rs
  godot-core/src/meta/godot_convert/mod.rs
  godot-core/src/obj/raw_gd.rs
  itest/rust/src/builtin_tests/containers/variant_test.rs
  itest/rust/src/object_tests/object_test.rs
Labels: bug, c: core, ub

#1034 Support `Variant::object_id()` for Godot <4.4; add `object_id_unchecked()`
  godot-core/src/builtin/variant/mod.rs
  godot-core/src/meta/error/convert_error.rs
  itest/rust/src/builtin_tests/containers/variant_test.rs
Labels: quality-of-life, c: core

#1035 Rename `Basis` + `Quaternion` methods, closer to Godot
  godot-core/src/builtin/basis.rs
  godot-core/src/builtin/mod.rs
  godot-core/src/builtin/quaternion.rs
  godot-core/src/builtin/transform3d.rs
  godot-core/src/obj/guards.rs
  itest/rust/src/builtin_tests/geometry/basis_test.rs
Labels: quality-of-life, c: core

#1036 Compare scripts via object_id
  godot-core/src/obj/script.rs
Labels: quality-of-life, c: core

#1023 Speed up creating and extending packed arrays from iterators up to 63×
  godot-core/src/builtin/collections/extend_buffer.rs
  godot-core/src/builtin/collections/mod.rs
  godot-core/src/builtin/collections/packed_array.rs
  itest/rust/src/benchmarks/mod.rs
  itest/rust/src/builtin_tests/containers/packed_array_test.rs
Labels: c: core, performance

#1044 Add godot 4.3 to minimal CI
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
Labels: quality-of-life, c: tooling

#1041 fix clippy warnings: this looks like a formatting argument but it is not part of a formatting macro
  itest/rust/src/builtin_tests/geometry/quaternion_test.rs
Labels: bug, c: tooling

#1045 Global main thread ID
  godot-core/build.rs
  godot-core/src/init/mod.rs
  godot-ffi/src/binding/single_threaded.rs
  godot-ffi/src/lib.rs
Labels: feature, c: ffi

#1050 Add .uid files for GDScript + GDExtension resources; update script cache
  .github/composite/godot-itest/action.yml
  examples/hot-reload/godot/rust.gdextension.uid
  examples/hot-reload/godot/test/ReloadOrchestrator.gd.uid
  examples/hot-reload/godot/test/ReloadTest.gd.uid
  itest/godot/.godot/global_script_class_cache.cfg
  itest/godot/InheritTests.gd.uid
  itest/godot/ManualFfiTests.gd.uid
  itest/godot/ScriptInstanceTests.gd.uid
  itest/godot/SpecialTests.gd.uid
  itest/godot/TestRunner.gd.uid
  itest/godot/TestSuite.gd.uid
  itest/godot/TestSuiteSpecial.gd.uid
  itest/godot/itest.gdextension.uid
Labels: quality-of-life, c: tooling

#1030 Add "validate_property" virtual func
  godot-codegen/src/generator/virtual_traits.rs
  godot-core/src/builtin/string/gstring.rs
  godot-core/src/builtin/string/string_name.rs
  godot-core/src/meta/property_info.rs
  godot-core/src/obj/traits.rs
  godot-core/src/registry/callbacks.rs
  godot-core/src/registry/class.rs
  godot-core/src/registry/plugin.rs
  godot-macros/src/class/data_models/interface_trait_impl.rs
  itest/rust/src/object_tests/mod.rs
  itest/rust/src/object_tests/object_test.rs
  itest/rust/src/object_tests/validate_property_test.rs
Labels: feature, c: ffi

#1049 Add #[allow(...)] directives to macro-generated entries
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/derive/derive_from_godot.rs
Labels: quality-of-life, c: register

#1055 Fix clippy: operator precedence can trip the unwary.
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  .github/workflows/release-version.yml
  check.sh
Labels: quality-of-life, c: tooling

#1053 Register-docs: Don't duplicate brief in description
  godot-core/src/docs.rs
  itest/rust/src/register_tests/res/registered_docs.xml
Labels: bug, c: register

#1056 Fix `DynGd<T,D>` export, implement proper export for `Array<DynGd<T,D>>`
  godot-core/src/obj/dyn_gd.rs
  godot-core/src/obj/gd.rs
  godot-core/src/registry/class.rs
  godot-core/src/registry/plugin.rs
  godot-core/src/registry/property.rs
  itest/rust/src/object_tests/dyn_gd_test.rs
Labels: bug, c: register

#1058 Move some compile-time validations from godot to godot-ffi
  godot-ffi/src/lib.rs
  godot/src/lib.rs
Labels: bug, c: tooling

#1002 Correct `ConnectFlags` classification (enum -> bitfield)
  godot-codegen/src/models/domain_mapping.rs
  godot-codegen/src/special_cases/special_cases.rs
Labels: quality-of-life, c: engine, breaking-change

#1000 Type-safe signals
  .github/workflows/full-ci.yml
  godot-core/src/builtin/mod.rs
  godot-core/src/classes/class_runtime.rs
  godot-core/src/meta/mod.rs
  godot-core/src/obj/gd.rs
  godot-core/src/obj/raw_gd.rs
  godot-core/src/obj/script.rs
  godot-core/src/obj/traits.rs
  godot-core/src/private.rs
  godot-core/src/registry/mod.rs
  godot-core/src/registry/signal/connect_builder.rs
  godot-core/src/registry/signal/mod.rs
  godot-core/src/registry/signal/typed_signal.rs
  godot-core/src/registry/signal/variadic.rs
  godot-macros/src/class/data_models/func.rs
  godot-macros/src/class/data_models/inherent_impl.rs
  godot-macros/src/class/data_models/rpc.rs
  godot-macros/src/class/data_models/signal.rs
  godot-macros/src/class/derive_godot_class.rs
  godot-macros/src/docs.rs
  godot-macros/src/lib.rs
  godot-macros/src/util/mod.rs
  godot/src/lib.rs
  godot/src/prelude.rs
  itest/rust/src/builtin_tests/containers/signal_test.rs
  itest/rust/src/engine_tests/native_audio_structures_test.rs
  itest/rust/src/framework/mod.rs
  itest/rust/src/object_tests/object_test.rs
  itest/rust/src/object_tests/reentrant_test.rs
  itest/rust/src/register_tests/func_test.rs
Labels: feature, c: register, breaking-change

#1029 `Callable::from_local_static()` now requires Godot 4.4+
  godot-core/src/builtin/callable.rs
  godot-core/src/builtin/variant/mod.rs
  godot-core/src/meta/error/convert_error.rs
  itest/rust/src/builtin_tests/containers/callable_test.rs
Labels: bug, c: core, breaking-change
